### ISSUE TITLE
"Disable sound effects" and "Disable audio effects"

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#1]
![untitled](https://cloud.githubusercontent.com/assets/15729831/12571669/e8736550-c415-11e5-8982-2b129eaeeb6f.png)
Why there are both "Disable sound effects" and "Disable audio effects"?
The "Disable sound effects" does nothing. Just remove that.

**Comment by KaleidonKep99** [comment]
"Disable audio effects" actually does a lot.
It removes the BASS_SAMPLE_FX flag, allowing BASS to reduce its latency to a value less than 150ms.
