### ISSUE TITLE
Keppy's Driver won't turn up in any MIDI Player I try.

### ISSUE THREAD

**Issue by soxxxx** [KaleidonKep99/OmniMIDI#10]
It isn't working even though Coolsoft VMSis uninstalled.

**Comment by KaleidonKep99** [comment]
You need to install Visual C++ 2013, both 32-bit and 64-bit versions.

**Comment by DevanWolf** [comment]
Did you disable XAudio?

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
