### ISSUE TITLE
"Cap input framerate to 60FPS" checkbox doesn't work

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#101]
The checkbox doesn't work anymore. I can click it, but after saving the settings, it just reverted to whatever it was before. Looking into the registry, I noticed that there's an extra key: CapFramerrate (2 r instead of 1). I guess the driver doesn't read and write to the same key.
![image](https://user-images.githubusercontent.com/15729831/43991003-062ab036-9d8e-11e8-8e61-f40ac914e09e.png)

**Comment by longnguyen2004** [comment]
or maybe i'll make a pull request instead, if i know where it messes up :D

**Comment by KaleidonKep99** [comment]
That still won't make any difference, how am I supposed to compile it? lol

**Comment by KaleidonKep99** [comment]
Fixed.
