### ISSUE TITLE
setup wont run

### ISSUE THREAD

**Issue by NikoB999** [KaleidonKep99/OmniMIDI#11]
im trying to run the setup and it wont work

**Comment by KaleidonKep99** [comment]
What version of Windows do you have, and are you sure you're an administrator?

**Comment by NikoB999** [comment]
I'm on windows 7 64x and I'm the administrator

**Comment by KaleidonKep99** [comment]
I don't understand what you mean by "It won't work".

It doesn't open at all, or it gives you an error?

**Comment by NikoB999** [comment]
it runs in the background and i cant see it

**Comment by KaleidonKep99** [comment]
Try this: http://www.howtogeek.com/howto/windows/bring-misplaced-off-screen-windows-back-to-your-desktop-keyboard-trick/

**Comment by NikoB999** [comment]
was i supposed to uninstall vitrualMIDIsynth because an error came up

**Comment by NikoB999** [comment]
![error](https://cloud.githubusercontent.com/assets/19804922/15881372/147ea666-2cfb-11e6-873a-9ce35fbf3a7e.png)

**Comment by KaleidonKep99** [comment]
Yes, you need to uninstall it.

**Comment by KaleidonKep99** [comment]
So... Does it work?...

**Comment by KaleidonKep99** [comment]
I guess I can close this.
