### ISSUE TITLE
Fatal Execution Error on opening PFA

### ISSUE THREAD

**Issue by lewisakura** [KaleidonKep99/OmniMIDI#111]
![](https://pantsu.review/940650.png)

I have no clue what the issue is, I just installed the driver after removing Keppy's Synthesizer and I'm getting this when I open PFA.

Could it be related to this?
![](https://pantsu.review/bc95ef.png)
Log file of the above error:
```
Debug log of "OmniMIDI - Error"
=================
Friendly text:
An error has occurred while loading the driver's settings.

Exception reason:
System.NullReferenceException: Object reference not set to an instance of an object.
   at OmniMIDIConfigurator.Functions.LoadSettings(Form thisform)
=================
Date: October 13, 2018 - 11:41:02.461 AM
```

If I run the configurator as administrator (Right Click > Run as Administrator) I can't reproduce the above error, but this is really annoying to do.

**Comment by lewisakura** [comment]
Appears if I run PFA as administrator it doesn't error out like it did, but it still requires me to run it through the context menu. I've never had this issue before with the original Keppy's Synthesizer, was something changed that requires administrator privileges?

**Comment by lewisakura** [comment]
![](https://pantsu.review/782677.gif)

Erm..

**Comment by KaleidonKep99** [comment]
Open regedit, go to **"Computer\HKEY_CURRENT_USER\Software\OmniMIDI"**, and delete the OmniMIDI key.

**Comment by lewisakura** [comment]
Well, I can open PFA now, but..
![](https://pantsu.review/f2deb3.png)

**Comment by lewisakura** [comment]
Good news!

After reinstalling the driver from scratch (through the configurator) it's all working!

![](https://pantsu.review/20e2b9.png)
Looks like there must've been some left over data that was causing issues with OmniMIDI.

**Comment by KaleidonKep99** [comment]
You should've used the official KStoOM tool (KS downloads it automatically when you check for updates), instead of updating manually by yourself!
Closed.

**Comment by lewisakura** [comment]
In my defense I didn't know that tool existed, and KS didn't download it when I told it to update.

Thanks for pointing me to the registry key though, guess it did help me out!

**Comment by SebaUbuntu** [comment]
I have this problem too, and I have reinstalled previous version to avoid this problem (I have even tried to delete registry keys, but I can't play any MIDI with any player with version 6.0.44)

**Comment by lewisakura** [comment]
@SebaUbuntu I recommend opening a new issue instead of commenting on this.

**Comment by SebaUbuntu** [comment]
Yes, but i think is the new version or Windows 10 that have broken something, now with the old version it work all except I can't use the option to load SF on RAM, it give me the same error.

**Comment by lewisakura** [comment]
Huh.

**Comment by KaleidonKep99** [comment]
Please create another issue on GitHub for that.
