### ISSUE TITLE
Error 0x6: The handle is invalid

### ISSUE THREAD

**Issue by SebaUbuntu** [KaleidonKep99/OmniMIDI#112]
![screenshot 8](https://user-images.githubusercontent.com/38215111/47795405-cba4c580-dd22-11e8-9460-6a0a03d1847b.png)
When I try to use Omnimidi ≥6.0.44 I can't use it with any application because of this error, I use soundfonts that are more than 2 GB.

**Comment by KaleidonKep99** [comment]
That doesn't appear to be an error message related to SoundFonts. The driver closes the registry handles only when the MIDI app sends MODM_CLOSE to the driver (For example, if the MIDI app is switching MIDI drivers or it's shutting itself down).

I suggest reinstalling the driver from scratch, that usually fixes these issues with the registry.
![image](https://user-images.githubusercontent.com/11065274/47802187-095c1b00-dd30-11e8-8894-04ac505aef94.png)

**Comment by SebaUbuntu** [comment]
![screenshot 10](https://user-images.githubusercontent.com/38215111/47803140-1bd75400-dd32-11e8-8017-0bb5ab760f85.png)
This happen after Omnimidi have downloaded the installer
P.S. This happen in 2 different device

**Comment by KaleidonKep99** [comment]
Oops, that might be an error of mine in the updater code! I'll fix it ASAP.

**Comment by KaleidonKep99** [comment]
https://github.com/KeppySoftware/OmniMIDI/releases/tag/6.0.49.0

**Comment by SebaUbuntu** [comment]
There is the same error 0x6 even reinstalling the driver from scratch from version 6.0.49

**Comment by SebaUbuntu** [comment]
I have tried even with DirectX audio, but it doesn't work
How can I send you a log?

**Comment by KaleidonKep99** [comment]
![image](https://user-images.githubusercontent.com/11065274/47828862-017a9600-dd85-11e8-9979-8ea216fc8e3c.png)
You can enable the debug log from here.

**Comment by SebaUbuntu** [comment]
Now it load all the soundfont but it stop immediately the playback in Windows Media Player, MIDIBar (a MIDI player integrated in MIDI-OX), after you have selected Omnimidi as a MIDI synth and selected a file to play it say this:
![screenshot 1](https://user-images.githubusercontent.com/38215111/47850304-10893480-ddd5-11e8-9af6-84da870938e4.png)
But the log files didn't show up any error:
[Midibar.exe - 01-11-2018 11.48.35 (Debug output).txt](https://github.com/KeppySoftware/OmniMIDI/files/2538386/Midibar.exe.-.01-11-2018.11.48.35.Debug.output.txt)

**Comment by SebaUbuntu** [comment]
I don't know what to do, it happen in 2 different PC that I have

**Comment by SebaUbuntu** [comment]
MIDI-OX say this:
![screenshot 2](https://user-images.githubusercontent.com/38215111/47850445-8d1c1300-ddd5-11e8-9984-69228247d84a.png)
But I have 8 GB of RAM, and it take only 15% of RAM available
And, ignoring the error, with MIDI-OX it work, it can output sound

**Comment by SebaUbuntu** [comment]
And I can play MIDI using this method:
Windows Media Player (or any other MIDI player)>LoopMIDI>MIDI-OX>Omnimidi

**Comment by KaleidonKep99** [comment]
SysEx messages should work fine now, sorry! *(It was a typo in the source code, oops!)*
https://github.com/KeppySoftware/OmniMIDI/releases/tag/6.0.50.0

**Comment by KaleidonKep99** [comment]
Fixed, *chiuso!* :P
