### ISSUE TITLE
OmniMIDI is idk bugging?

### ISSUE THREAD

**Issue by PyroMorph** [KaleidonKep99/OmniMIDI#113]
![capture 1](https://user-images.githubusercontent.com/44757180/47971067-43843000-e042-11e8-8595-5c989fa9ed58.PNG)

**Comment by PyroMorph** [comment]
Okay nevermind now it worked. I'm sorry for the inconvenience i've brought.

**Comment by KaleidonKep99** [comment]
Closed I guess? Lel
