### ISSUE TITLE
you can add option for add note lenght overwrite? (Default as 0)

### ISSUE THREAD

**Issue by MIDAPMI** [KaleidonKep99/OmniMIDI#114]
i am creating mobile SF2 sound banks, but original synth use different note override

example the 1/4 (480) 
note in beatnik is the equivalent to 490 in bassmiidi
Synthfont is equivalent to 490 in bassmidi
fluidsynth is equivalent to 490 in bassmidi
in series 30 of nokia (work correctly)
Symbian OS, Series 40 from 3rd fp2 uses beatnik (490 in bassmidi)
Series 40 3rd edition uses 500-505 aprox in bassmidi
Series 40 2nd edition (6230i) uses 490 in bassmidi
Series 40 2nd edition (3220 and above) uses 490 in bassmidi.

This value is necesary and usefully for me and others mobile developers

**Comment by KaleidonKep99** [comment]
Sorry, but I'm not the developer of that library.
You could ask Ian Luck from Un4seen to implement something like this in my driver, I'll be happy to include it in the next release.

Here's his forum: https://www.un4seen.com/forum/

**Comment by MIDAPMI** [comment]
yes, please implement, is excellent ideas for mobile-sf2. thanks, great driver :)

The next is newers mobile sound banks releases for very improvisation of midi drivers

Mobile Sound banks
1 - Series 30 (Nokia 1000 Series) (not is 100% exactly because need cc#7 to velocity curve)
2 - Series 40 2nd edition (Nokia 3000 series) [FM simulation]
3 - Series 40 2nd edition lite (Nokia 6000 series)
4 - Series 40 3rd edition FP2 (Nokia 5000 Series and XM series)
5 - Series 40 5th/6th edition lite series (2000 series) with help of ryan zmey
6 - Huawei BREW OS 4.0 (Huawei C****/U**** series without android)
7 - Series 60 (Symbian)

**Comment by KaleidonKep99** [comment]
Duplicate.
