### ISSUE TITLE
The configurator doesn't save the lists correctly

### ISSUE THREAD

**Issue by SebaUbuntu** [KaleidonKep99/OmniMIDI#116]
Activating "Enable debug log" doesn't create any log file;
This are dumps from Windows Event Viewer:
[error.zip](https://github.com/KeppySoftware/OmniMIDI/files/2554479/error.zip)
If I use Microsoft GS synth, WMPlayer works

**Comment by KaleidonKep99** [comment]
There was no need to open another issue, I could've just reopened the previous one! :P

By the way, I already fixed the issue. Apparently, Windows Media Player is pretty strict, when it comes to memory usage during initialization. I managed to get around it though.

I'll post the working release asap.

**Comment by SebaUbuntu** [comment]
Now it works, really thanks 👍

**Comment by KaleidonKep99** [comment]
Closed!

**Comment by SebaUbuntu** [comment]
Wait a minute, I've added a SFZ and now it won't work anymore, now it doesn't produce any sound, I've even tried uninstall Omnimidi and reinstall, deleted Omnimidi registry keys, but it won't work, what can I do?

**Comment by KaleidonKep99** [comment]
Oh no!
I just found out that there's a bug in the configurator, which incorrectly saves the SoundFont lists...
This is what I get for not testing my app enough... 
But this is also my Achilles heel, I have no testers that can help me test the driver in real-time, so I have to either find the bugs by myself, or wait for someone else to have issues with it...

I'm deeply sorry, I'll fix this issue asap.

**Comment by KaleidonKep99** [comment]
This should be it! Sorry again.
https://github.com/KeppySoftware/OmniMIDI/releases/tag/6.0.55.0

**Comment by SebaUbuntu** [comment]
Hey! No problems 👍

**Comment by SebaUbuntu** [comment]
But only one thing: For whoever have already downloaded version 6.0.55 they don't receive any notification about re-release

**Comment by KaleidonKep99** [comment]
I'm pushing 6.0.56 to notify everyone!
Closed.
