### ISSUE TITLE
Question: Is there a chance in the future to create multiple MIDI virtual device?

### ISSUE THREAD

**Issue by SebaUbuntu** [KaleidonKep99/OmniMIDI#117]
I use a notation software called Finale, and it support up to 8 MIDI out devices for big sheet music, and I was thinking if you can implement this feature, can it be possible?

**Comment by KaleidonKep99** [comment]
OmniMIDI used to be a two port synthesizer, back when it was a mod for BASSMIDI Driver, but I decided to drop support for that to introduce a more flexible dynamic SoundFonts list system.

I'll see what I can do about it, but no promises.

**Comment by SebaUbuntu** [comment]
Ok, thanks

**Comment by KaleidonKep99** [comment]
On hold.
