### ISSUE TITLE
note lenght delay

### ISSUE THREAD

**Issue by MIDAPMI** [KaleidonKep99/OmniMIDI#118]
http://www.un4seen.com/forum/?topic=18303 here the data for add (if is in ms is better)

Perfectly for MSB (Mobile Sound Banks)

> i am creating mobile SF2 sound banks, but original synth use different note override
> 
> example the 1/4 (480)
> note in beatnik is the equivalent to 490 in bassmiidi
> Synthfont is equivalent to 490 in bassmidi
> fluidsynth is equivalent to 490 in bassmidi
> in series 30 of nokia (work correctly)
> Symbian OS, Series 40 from 3rd fp2 uses beatnik (490 in bassmidi)
> Series 40 3rd edition uses 500-505 aprox in bassmidi
> Series 40 2nd edition (6230i) uses 490 in bassmidi
> Series 40 2nd edition (3220 and above) uses 490 in bassmidi.

This value is necesary and usefully for me and others mobile developers.

Preferable in ms

**Comment by KaleidonKep99** [comment]
It'll be ready in a few days.
