### ISSUE TITLE
MIDI player hangs on latest version of driver

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#12]
The latest version (3.2.0.4) hangs the MIDI application when the MIDI application opens Keppy's Driver. Version 3.2.0.3 works fine.

**Comment by KaleidonKep99** [comment]
Oopsie, I guess it's a side effect of the new System Processes Blacklist System.
I'll fix this asap.

**Comment by KaleidonKep99** [comment]
Uh oh, it was actually my fault!

Here's the error:
`

```
if (!_tcsicmp(modulename, bannedconsent) | !_tcsicmp(modulename, bannedexplorer) | !_tcsicmp(modulename, bannedcsrss) == 0) {

    return TRUE;

    // It's a blacklisted process, so it can NOT create a BASS audio stream.

}
```

`
I forgot to remove "== 0" from an old test version of the blacklist, I fixed it now.

I'm going to release 3.2.0.5.

**Comment by KaleidonKep99** [comment]
[Version 3.2.0.5 of Keppy's Driver.](https://github.com/KaleidonKep99/Keppy-s-Driver/releases/tag/3.2.0.5)
