### ISSUE TITLE
Note length delay is not correctly, or bad configured

### ISSUE THREAD

**Issue by MIDAPMI** [KaleidonKep99/OmniMIDI#122]
The idea is override example,
i
when midi sends one note with a 480 length if i set to 20 ms, this need replace as 480+20 ms no directly replace the note 480 with only 20 ms. is good idea for black midi but for emulate mobile phones no work well. same to 120 note lenght replaced with 120+20ms. is delay between note off event and release. 

if the error is of ian answer comment for request this to ian

**Comment by KaleidonKep99** [comment]
Added function to version 6.0.57.16.

**Comment by MIDAPMI** [comment]
Thanks keepy for contribute with mobile sound banks developers! but still. not work correctly. continues replacing notes event. what is problem i have the option only release the older instance. 

example when i set to delay 0.020 ms need stay to this foto, no is override note lenght is delay after note off.

i
![sin titulo](https://user-images.githubusercontent.com/44755104/48750668-1731fb80-ec5f-11e8-8589-d0155f98b36f.jpg)

**Comment by KaleidonKep99** [comment]
![image](https://user-images.githubusercontent.com/11065274/48770482-b6d2a680-ecbe-11e8-9f78-c4f998148653.png)
You need to disable the **"Override length of note events"** function!

**Comment by MIDAPMI** [comment]
Thanks fixed! when i test, in some midi not work well. (or work with some channel and others not)
