### ISSUE TITLE
"Out of range error" when velocity ignoring is enabled

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#123]
On every MIDI, when the first note plays, this error pops up
[img]https://i.imgur.com/gtlsWOa.png[/img]
Tried both with and without KDMAPI patch

**Comment by KaleidonKep99** [comment]
Oh yes, it's a mistake in the DebugResult function.
The actual error is MMSYSERR_MOREDATA, TMIDI keeps sending more MIDIHDR pointers without waiting for OmniMIDI to complete reading the previous ones.

**Comment by KaleidonKep99** [comment]
![image](https://user-images.githubusercontent.com/11065274/48770253-f8168680-ecbd-11e8-805d-fd3fa2722d16.png)
Even though I've been trying MIDIs on TMIDI for about 20 minutes, and I haven't seen the message once.

**Comment by KaleidonKep99** [comment]
Check what the error is after updating to .17!

**Comment by longnguyen2004** [comment]
alright i'll check it when i come back home

**Comment by longnguyen2004** [comment]
eh nope, it was the "Ignore notes in between two velocity values" that caused the error, changed title

**Comment by KaleidonKep99** [comment]
Ok, after some debugging, the actual error is MIDIERR_NOTREADY.
It will be fixed on the next release.

**Comment by KaleidonKep99** [comment]
Fixed.
