### ISSUE TITLE
TIMIDITY++ features for OMNIMIDI

### ISSUE THREAD

**Issue by MIDAPMI** [KaleidonKep99/OmniMIDI#125]
![image](https://user-images.githubusercontent.com/44755104/48965857-09a0ac80-efa4-11e8-8074-65352111554f.png)

Request for mobile soundfonts! Thanks i a good for series 30 (very nostargic). and you can take some configurations for timidity for your driver Good job!!!

**Comment by MIDAPMI** [comment]
> This seems to be controlled internally by the TiMidity engine, not by the WINDRV wrapper itself. 
> Could you ask Ian Luck about this as well? I don't think that can be done with DWORDs, afaik.

Yes, timidity work well inclusive with windrv.

Example the curve is well

you can set linear or concarve curve in  CC#7 events.

For improve your driver i can recommend some features from mobile engines. i ask to ian for this question and others features. 

Postdata: Falcosoft no are in agreement thats ian add more mobile features ¿Why?. I don't know. xD.

**Comment by Falcosoft** [comment]
@MIDAPMI: I have not said anything like that. Ian does not need my agreement for anything anyway...
I said exactly this:

![conv1](https://user-images.githubusercontent.com/40074203/49123547-437df580-f2b9-11e8-8ebd-cd2bfe55c710.jpg)

**Comment by MIDAPMI** [comment]
> @MIDAPMI: I have not said anything like that. Ian does not need my agreement for anything anyway...
> I said exactly this:
> 
> ![conv1](https://user-images.githubusercontent.com/40074203/49123547-437df580-f2b9-11e8-8ebd-cd2bfe55c710.jpg)

Yes, is for midiplayer you not agreement. but for driver is good ideas?

**Comment by KaleidonKep99** [comment]
I don't think Ian Luck will add this feature, since it's not part of the SF2 standard.

**Comment by MIDAPMI** [comment]
It's for request DRC for mobile devices

I want go to Google forum for ask about MXMF or similar format for MOD3 Meta Xtended Music Mobile Files Synthetizer on BASS for basic devices (it's best player by me for mobile devices).  for replace the nokia very old MXMF based on Meta extended music format. For loud mobile phones can be used this format with limiter of phone. android not support MXMF  or some phones have beatnik, i don't know in reality. but i'm secure have better quality with practically the same features of MXMF

I only know how for make Music Xpress Mobile Fonts (.xmf) midi music (.mid) and create  the further MMMF files (called  by me as MOD3 Synthetic Music Mobile Files), and program Mobile Sound Banks! but i don't know how to program in c++ and other users and youtube also don't know. Omnimidi with all ideas can be used as project with industries in mobile phones and midiplayer as SDK for MXMF MOD3 Xtended Music Files (also as MOD3). not is great idea. some phone have sound limiter with DRC (Dynamic Range Compressor) Example Nokia 6500 uses attack of 100 ms and release of 2000 (release is actually supported with omnimidi as note off delay) with aspect relationship 2000:1000 (like Windows Generic Audio Driver Dynamic Range Compressor "Called as equalizer). This reduce clips in speaker of some phones. but if you use 24 bits midi in 8 bit speaker the sound is bad and phone.

My huawei of this video have fully DRC

but android not. have same volume for 8 bits music (So in  MP3 in 32 kB format the sound is very loud but no have DRC and the result is blurred more music and if i want send 128 bits music for great quality loud the phone but automatically reduces volume" (this is the reason of the Xpress music it was so desired in your time.)

This is well idea for LAN for make money with more donation from all peoples of the world.

Example you have your grandmother need one phone use this for call and receives message. in case of my grand mother, he do  not have interested in high quality music but the volume of phone is same in all music resolution and when touch phone for write message and reply call or answer call the phone go to all sites except can't be answer call reply call or write message (Practically no know how to use phone).

from my point of view android not have consideration with senior people.

I have working All series including the OLD Yamaha SMAF Autorithing tool and MSB Mobile DLS Sound Banks. for lite devices. The stupid basic phones lastest of nokia have only support of midi and MMF. (This not have limiter (in 8 bit 16 bits or 24 bits) without DLS or SF2 support. and android only working with limiter not have DRC (The majority of people like the nokia generic driver because this have DRC).

> I don't think Ian Luck will add this feature, since it's not part of the SF2 standard.

Yes for desktop but for devices ringtones not is well if IAN want implement MOD3 your tecnology in phones. need take this

![image](https://user-images.githubusercontent.com/44755104/49196032-b5a91580-f35f-11e8-9833-da8a1f8e49dc.png)

This is based in the WDM Generic Driver. this can reduce clips on phone.

MXMF

can be this values with mod3 file :+1:

**Comment by MIDAPMI** [comment]
Practically is MOD3 for android -.- but with DRC Limiter what is problem.
