### ISSUE TITLE
Configurator crashes when saving with blank value of sample rate

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#13]
A blank sample rate should only give the default value of the sound card/audio device's sample rate rather than the fixed value. But instead the configurator crashes when you apply changes with no sample rate. This is why we need support for audio device's default sample rate.

**Comment by KaleidonKep99** [comment]
I didn't understand what you meant by this message... Could you explain better?

**Comment by DevanWolf** [comment]
I prove you that I got this:
![](https://cloud.githubusercontent.com/assets/8494722/15914645/43c301f8-2da8-11e6-9ef1-c5175e487769.png)
(Notice the empty value in the sample rate)

**Comment by KaleidonKep99** [comment]
Oooooh I see what you mean now.

_Fixed as of version 3.2.0.7._
