### ISSUE TITLE
Signatures are not matching in latest release (6.1.0.0)

### ISSUE THREAD

**Issue by B00ie23** [KaleidonKep99/OmniMIDI#131]
**Problem**
I recently updated to the latest release of OmniMIDI. From time to time, I would check driver signatures to be sure that I didn't break it accidentally when configuring settings. When I looked after updating, the provided signatures did not match the expected signatures. I used the installer the configurator provided.

**Steps to reproduce**
1. Open Configurator
2. Tools -> Check the driver signature for tampering
(steps provided if needed)

**Screenshots/Videos**
![Capture](https://user-images.githubusercontent.com/45867359/50728670-64b8d980-10e2-11e9-9a41-a369dabafb97.PNG)

**Environment**
 - Operating system: Windows 10 Home
 - CPU: Intel Core i3-6100
 - RAM: 16.0 GB
 - MIDI application: None
 - Version of the driver: 6.1.0.0

**Additional context**
Driver-provided signatures are the same when using the installer from here or from the driver, but neither of those match the expected signatures. You may notice the "There's also an update available" message, clicking that returns with "No updates found" (since I'm using the latest release.)

**Comment by KaleidonKep99** [comment]
Oops! I'll fix that asap.

**Comment by KaleidonKep99** [comment]
Fixed in version 6.2.
