### ISSUE TITLE
OmniMIDI not appears in the windows Midi output list

### ISSUE THREAD

**Issue by ghost** [KaleidonKep99/OmniMIDI#132]
**Problem**
OmniMIDI does not appear in my midi list

**Steps to reproduce**
1. I used the register/unregister for fix the problem
2. Uninstal/reinstal the app
3. Retry twice 

**Expected behavior**
Can’t see OmniMIDI on the list

**Screenshots/Videos**
Doesn’t have one

**Environment**
 - Operating system: Windows XP
 - CPU: Intel Pentium III Xeon x86
 - RAM: 1gb
 - MIDI application : PFA 1.1.0 x86
 - Version of the driver: x.x.x.x

**Additional context**
I don’t have .NET Framework

**Comment by KaleidonKep99** [comment]
OmniMIDI requires at least Windows Vista to work.
https://github.com/KeppySoftware/OmniMIDI#required-software-for-it-to-work
