### ISSUE TITLE
Note delay doesn't work well

### ISSUE THREAD

**Issue by MIDAPMI** [KaleidonKep99/OmniMIDI#133]
Why doesn't work well with some midi/channels.

you can fix this?

**Comment by KaleidonKep99** [comment]
The delay option only affects NoteON and NoteOFF events sent to the driver through short messages (midiOutShortMsg).
If the player sends the events through other means (long messages/midiOutLongMsg or midiStreamOut) the option will not work.

**Comment by MIDAPMI** [comment]
You can add option for force note off delay?
[test.zip](https://github.com/KeppySoftware/OmniMIDI/files/2887658/test.zip)
show this (difference is between 13-20 ms)

**Comment by KaleidonKep99** [comment]
The option in the configurator already does that, but again, I can't add delay to long or stream messages.

**Comment by MIDAPMI** [comment]
:( Beatnik take more natural music and smoother sound with this option. i don't know why if i import this in synthfont and export the driver work well but original not work.

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
