### ISSUE TITLE
"The handle of the specified device is invalid." when using Windows Media Player to play a midi

### ISSUE THREAD

**Issue by thegreatestminer** [KaleidonKep99/OmniMIDI#134]
**Problem**
Any MIDI refuses to play on Windows Media Player and gives a handle error.

**Steps to reproduce**
1. Play MIDI flourish.mid on application wmplayer.exe

**Expected behavior**
MIDI should play regularly.

**Screenshots/Videos**
[YouTube video showing the error](https://www.youtube.com/watch?v=xkaFoXsIRfM&feature=youtu.be)

**Environment**
 - Operating system: Windows 7 Home Premium (x64)
 - CPU: Pentium(R) Dual-Core CPU E6700 @ 3.20GHz
 - RAM: 3GB
 - MIDI application: wmplayer.exe (Version 12.0.7601.24312)
 - Version of the driver: 6.3.0, Canary Build 8

**Additional context**
Attempting to run a MIDI on another player (i.e. MAMPlayer) has very broken audio and ultimately freezes when attempting to pause and resume playback. I was not able to get UMP to run, so no info for that.

**Comment by thegreatestminer** [comment]
Forgot to post the debug logs.

https://pst.moe/paste/yowgnq - wmplayer.exe - 20-02-2019 23.16.56 (Debug output).txt
https://pst.moe/paste/hyearw - MAMPlayer.exe - 20-02-2019 23.17.03 (Debug output).txt

**Comment by KaleidonKep99** [comment]
The latest changes to the midiStream system might be to blame. WMP will be fixed soon.

About MAMPlayer, we've never been able to get it to work. It seems to require some features that we don't know about. We'll definitely still try to get it to work though, just like we did with EDuke32.
Try playing your MIDIs on another MIDI player, like vanBasco or TMIDI. If they don't crash, then it's the MAMPlayer issue we were talking about.

**Comment by KaleidonKep99** [comment]
Fixed both MAMPlayer and Windows Media Player!
Release: https://github.com/KeppySoftware/OmniMIDI/releases/tag/6.3.0.9
