### ISSUE TITLE
Fallback To WASAPI when starting a MIDI Player with ASIO4ALL

### ISSUE THREAD

**Issue by OmerFlame** [KaleidonKep99/OmniMIDI#137]
Everytime I start Ultralight MIDI Player and in the OmniMIDI settings, I switched the renderer to ASIO (I installed ASIO4ALL), it falls back to WASAPI. How do I fix this?

P.S: I didn't restart after installing ASIO4ALL, so is that an issue?

**Comment by KaleidonKep99** [comment]
![immagine](https://user-images.githubusercontent.com/11065274/55291309-807c0500-53dd-11e9-9bfc-fd43d2245179.png)
You have to select a device!

**Comment by OmerFlame** [comment]
Thank you so much!

**Comment by OmerFlame** [comment]
Wait, I still get very high latency in some parts of the song... is it my problem or something in the settings?

P.S: I'm trying to play a Black MIDI file... Sorry for improfessionalism, I'm just starting to play with Black MIDI. I'm trying to play Septette For The Dead Princess 14.6 Million

**Comment by KaleidonKep99** [comment]
You have to configure ASIO4ALL for each app!
This icon will appear in the taskbar everytime an app is using ASIO4ALL.
![immagine](https://user-images.githubusercontent.com/11065274/55308261-79470c80-545a-11e9-809e-b69a5589d2ba.png)

Double click it and then edit the settings, then click the "Apply" button in the configurator while holding SHIFT to force restart the audio stream.
![immagine](https://user-images.githubusercontent.com/11065274/55308286-8a901900-545a-11e9-8df8-9c25c0735288.png)

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
