### ISSUE TITLE
Just had a problem with functions using OmniMIDI on PFA.

### ISSUE THREAD

**Issue by dermi1002** [KaleidonKep99/OmniMIDI#138]
Everytime I try to use OmniMIDI on PFA, I always get this error.
![OmniMIDI - Fatal execution error 4_10_2019 11_32_26 AM](https://user-images.githubusercontent.com/49495596/55905788-992bae00-5b87-11e9-91fe-16e2fb23d5cb.png)
Is this a common error?

**Comment by KaleidonKep99** [comment]
Uninstall OmniMIDI, then install the latest version available.
Post a debug log if possible, to help me pinpoint the issue. (More settings > Debug logging for troubleshooting > Enable debug log)

**Comment by dermi1002** [comment]
So I installed the newest version (with the start menu programs), but when I opened the configurator from the start menu, I got this: [Error Debug Log.log](https://github.com/KeppySoftware/OmniMIDI/files/3067305/Error.Debug.Log.log)

What do I do to fix this?

**Comment by KaleidonKep99** [comment]
That's really weird... Are you sure you installed it through the **Setup** version, and not the **Update** one?

Anyway, you could try and restore OmniMIDI through an hidden command line switch:
![immagine](https://user-images.githubusercontent.com/11065274/55959698-8a1e2c00-5c6b-11e9-8539-320abdbe64d3.png)

**Comment by dermi1002** [comment]
Yes. I'm sure I installed using the setup version. I'll try the command.

**Comment by dermi1002** [comment]
Nevermind. I installed KDMAPI for PFA and I got OmniMIDI working. Thanks for helping, though.
