### ISSUE TITLE
Keppy's Direct MIDI API only appears in FL Studio when a project file is open 

### ISSUE THREAD

**Issue by AG89** [KaleidonKep99/OmniMIDI#140]
**Problem**
When opening FL Studio from the exe KDMA (Keppy's Direct MIDI AP) does not appear and OmniMIDI and OmniMapper are the only choices. Whenever using an FLP to launch FL Studio KDMA is used but error message appears saying omnimidi has failed

**Steps to reproduce**
1. Open FL Studio and put OmniMIDI's port to 0
2. Close FL Studio and then open through an FLP
3. See error

**Expected behavior**
Fl Studio should open without KMDA and once you enable OmniMIDI, close the program, then open through an FLP, you should get your issue.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/22873716/56433888-82303e80-62a0-11e9-8109-2f7599d9c99a.png)
![image](https://user-images.githubusercontent.com/22873716/56433954-ae4bbf80-62a0-11e9-8033-cc3ae1dbe929.png)
https://streamable.com/g5syr

**Environment**
 - Operating system: Windows10Pro1809
 - CPU: i7-8700k
 - RAM: 16GBDDR4
 - MIDI application: FL Studio Version 20.0.3 Build 532
 - Version of the driver: Canary 6.7.1.1

**Additional context**

**Comment by KaleidonKep99** [comment]
FL Studio comes in two versions, 32-bit and 64-bit.
The FLP is either associated with the 32-bit or 64-bit version of FL, which explains why the other version doesn't load the wrapper.

You can not use the standard OmniMIDI output when using the Keppy's Direct MIDI API one, since you can only allocate one driver instance per application.

**Comment by AG89** [comment]
Thank you, I have found out how to manually fix the issue

**Comment by KaleidonKep99** [comment]
Care to share the steps you followed to fix the issue? They could help other people too.

**Comment by AG89** [comment]
I reinstalled FL Studio to fix it. I could do anything else that would work.
