### ISSUE TITLE
An error has been detected while executing the following function: hKeyFlush

### ISSUE THREAD

**Issue by axpokl** [KaleidonKep99/OmniMIDI#143]
**Problem**
Get error while I try call the function midiOutLongMsg:
An error has been detected while executing the following function:
hKeyFlush

**Steps to reproduce**
midiOutLongMsg(midiOut,@msghdr,sizeof(msghdr))
Issue does not happens with midiOutStream function

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/8140778/57194764-432b0a00-6f7d-11e9-811e-4a422516db24.png)

**Environment**
 - Operating system: Win10 1903
 - MIDI application: midiplayer3-for-BLACK-MIDI

https://github.com/axpokl/midiplayer3-for-BLACK-MIDI

**Comment by KaleidonKep99** [comment]
It makes no sense, midiOutLongMsg has nothing to do with registry keys...
Could you please send a debug log? It'd help more.

**Comment by axpokl** [comment]
Hi Keppy. May I know how can I generate debug log?

I have some further test, it seems that the error was not though while midiOutLongMsg, but midiStreamOpen(@midiOut,@midiOuti,1,0,0,0);, and it even fail with 32 bit version with error MMSYSERR_ERROR. And it eventurally failes while midiStreamClose(midiOut); However, the midiStreamOpen function works at least with 64 bit version, although there is still other issues.

The code works fine with VirturalMidiSynth and Microsoft Wavetable. 

The function entry is define like that:
Function midiStreamOpen(x1: LPHMIDISTRM; x2: LPUINT; x3: DWORD; x4: DWORD_PTR; x5: DWORD_PTR; x6:DWORD): MMRESULT;stdcall; external 'winmm.dll' name 'midiStreamOpen';

Both parameter midiOut and midiOuti are DWORD

**Comment by KaleidonKep99** [comment]
You can enable the debug log from here:
![immagine](https://user-images.githubusercontent.com/11065274/57324952-46eb9780-7109-11e9-8205-ba33a639e82e.png)

Why would you use midiStreamOpen for this anyway? If you're going to use midiOutLongMsg only, use midiOutOpen instead of midiStreamOpen.
cMidi should be -1 and not 1, and fdwOpen should be CALLBACK_FUNCTION!
E.g. midiStreamOpen(&midiOut, &midiOutID, -1, &dwCallback, &dwInstance, CALLBACK_FUNCTION);

**Comment by KaleidonKep99** [comment]
Please try using OmniMIDI 7.1 instead of 6.7.2 in your tests, to see if the latest version is affected

**Comment by axpokl** [comment]
Issue still occurs with 7.1, the new logs can be found here:
https://axpokl.com/OmniMIDI_Debug2.zip
https://axpokl.com/OmniMIDI_Debug3.zip
This time I erase the main part to output the Midi Message and I can confirm that the issue happens while calling midiOutClose(midiOut);.

**Comment by KaleidonKep99** [comment]
Ok, I now made OM check if the registry key address is valid before passing it to RegKeyFlush/RegKeyClose.
It'll be online with update 7.1.0.2.

**Comment by KaleidonKep99** [comment]
BTW I just tried sending notes through midiOutLongMsg myself, and it works fine.
So you should still use midiOutOpen instead of midiStreamOpen, imo. 😛

**Comment by axpokl** [comment]
Hi, It seems that the error was though after midiOutClose, which the registry key opened from my program has not yet been closed. From the debug logs it seems the issue also relate to driver but not registry, from the procmon the RegKeyFlush was also success. 

And the issue only happens when I load Black Midi file, which contains a lot of events. So I suspect this might also regards with memory usage. 

I've tried midiOutLongMsg and it seems working fine. So the issue only happening when we close or open the midi driver.

I will continue try exclude codes to narrow down what step may cause that issue.

**Comment by axpokl** [comment]
Thanks for the update. I've tried the newest version and the issue seems to be resolved.
Now I have another issue which through an exception while we call midiOutLongMsg after switch midiStream API to midiOut API. I will raise another ticket.
