### ISSUE TITLE
Debug pipes won't switch.

### ISSUE THREAD

**Issue by B00ie23** [KaleidonKep99/OmniMIDI#144]
**Problem**
The debug menu behaves normally even when only one application is open. If there are two or more, attempting to switch pipes shows the same application that was first opened, and doesn't change.

**Steps to reproduce**
1. Open a minimum of two MIDI applications (or run another instance of the first application)
2. Open the debug window
3. Try to switch between pipes
4. Debug of first application remains on the window, and doesn't show the other pipe(s)

**Expected behavior**
In my case, I had Domino and PFA running, Domino being the first MIDI application open. What should've happened was the pipe should've shown PFA's debug when selected to switch to.

**Screenshots/Videos**
https://www.youtube.com/watch?v=OlFCZ1yvKLM&t=21s

**Environment**
 - Operating system: Windows 10 Home (x64)
 - CPU: Intel Core i3-6100 @ 3.70 GHz
 - RAM: 16 GB
 - MIDI application: Domino (x32 w/ 4 GB Patch), Piano From Above (x64)
 - Version of the driver: 7.1.0.1

**Additional context**
None

**Comment by KaleidonKep99** [comment]
Fixed in 7.1.0.2.
