### ISSUE TITLE
[BUG] OmniMIDI doesn't load source and destination values properly from SoundFont lists

### ISSUE THREAD

**Issue by TheSOB88** [KaleidonKep99/OmniMIDI#147]
**Problem**
I am attempting to use presets from different soundfonts at the same time.

At first, I was attempting to take bank 0 of GS FluidSynth and assign it to bank 17 or 20, but that wasn't working at all. So given that I at the moment needed the piano sample, I set it up as you can see here:

![fatboy-GS-test](https://user-images.githubusercontent.com/1317264/61564929-8dcd0600-aa45-11e9-9095-bfb1706caafe.png)

Import FatBoy (all), then import preset 0 from bank 0 from GS FluidSynth. However, it just overwrites _every_ preset with GS FluidSynth's presets. 

I am aware that the lower the SF is on the list, the higher the priority is, and I was accounting for that. But it seems that no matter the options, OmniMIDI imports the entire soundfont for some reason.

I was initially testing this in NoteWorthy Composer 2.75a2 (NWC accesses the MIDI driver directly.) This also happens with a test MIDI file I've attached, playing in Windows Media Player 12.0.17134.799 using the Coolsoft MIDI Mapper (set to Omni, of course). The wrong "Tremolo Strings" preset gets loaded with this configuration either way. 

**Steps to reproduce**
1. Play MIDI fatboy-GS-test.mid from [fatboy-GS-test.zip](https://github.com/KeppySoftware/OmniMIDI/files/3412690/fatboy-GS-test.zip) on application Windows Media Player

**Expected behavior**
Preset 44 (strings) are played from the FatBoy soundfont, piano (0) is played from GS FluidSynth soundfont

**Actual behavior**
Both presets are played from the GS FluidSynth SF

**Environment**
Intel Core i5-5200U CPU@2.2GHz
RAM: 8GB
x64
 - MIDI application: NoteWorthy Composer 2.75a2, Windows Media Player 12.0.17134.799
 - Version of the driver: 7.1.7

**Additional context**
No debug log was created by OmniMIDI

**Comment by TheSOB88** [comment]
Oh yeah, I tried re: installing. Didn't Worked.

**Comment by KaleidonKep99** [comment]
I found the culprit in the source code, I'll push a new release in a few minutes.

**Comment by KaleidonKep99** [comment]
Fixed in version [7.1.8.0](https://github.com/KeppySoftware/OmniMIDI/releases/tag/7.1.8.0).

**Comment by TheSOB88** [comment]
It's happening again.

**Comment by KaleidonKep99** [comment]
> It's happening again.

I tried reproducing the issue, and it doesn't seem to occur for me.
I followed the steps of the original message, using FatBoy, FluidSynth GS and the test MIDI provided, and the stream seem to be using the right samples.
