### ISSUE TITLE
Applications crashing trying to open midi driver

### ISSUE THREAD

**Issue by pachuco** [KaleidonKep99/OmniMIDI#148]
**Problem**
Applications attempting to open OmniMIDI driver crash. TMIDI by Fummy survives and plays.
When enabling debug for the crashing applications, I get the following:

OmniMIDI Fatal Execution Error
Function: LoadSettings
Codes:
- 0x8007012B - O
- 0x8007001E - T

**Environment**
 - Operating system: Windows XP SP3
 - CPU: Intel Core 2 Duo E7600
 - RAM: 3 GB
 - Tested MIDI application: Tom's MIDI Player, CakeWalk 3, WinGroove A5
 - Version of the driver: 8.0.0.0

Attached are debug outputs and my settings.

**Comment by pachuco** [comment]
Ooops, files didn't attach for some reason: https://files.catbox.moe/rp5wvt.zip

**Comment by pachuco** [comment]
Crashes start occurring from version 7.1.7.0

**Comment by KaleidonKep99** [comment]
Now that's really weird.
I'll see what I can do, even though I can't do much for XP since I only have a VM.

**Comment by KaleidonKep99** [comment]
Fixed: https://github.com/KeppySoftware/OmniMIDI/releases/tag/8.1.0.0
