### ISSUE TITLE
Req: FluidSynth as alternate engine

### ISSUE THREAD

**Issue by pachuco** [KaleidonKep99/OmniMIDI#149]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
FluidSynth as an alternate engine to BASSMIDI.

**Comment by KaleidonKep99** [comment]
I'll see if it's feasible.
Care to say why you'd like FS as an alternative? Is there something wrong with BASSMIDI?

**Comment by pachuco** [comment]
The request was made on a whim, without solid arguments, besides "I think this would be neat".
I have no problems with BASSMIDI.

**Comment by KaleidonKep99** [comment]
Alright. Again, I'll see if it's feasible, and eventually push some beta releases.
