### ISSUE TITLE
Req: Automatic destination preset by file prefix for SFZ import

### ISSUE THREAD

**Issue by pachuco** [KaleidonKep99/OmniMIDI#150]
When importing SFZ, option to determine destination patch by numeral filename prefix in "%03u" format, maybe "%3u".

**Comment by KaleidonKep99** [comment]
I'll see what I can do about it.

**Comment by KaleidonKep99** [comment]
Working on it now.
Sorry for keeping you waiting...

**Comment by KaleidonKep99** [comment]
Added to 1.11.3.1.
