### ISSUE TITLE
sf2pack, sf3/sfogg, sf4, etc...  formats support

### ISSUE THREAD

**Issue by shadelegend333** [KaleidonKep99/OmniMIDI#153]
sf2pack: various encodings, included with BASSMIDI
sf3: Ogg compression format used by MuseScore
sfogg: K.O.R. and Falcosoft alternative (not sure what the difference is)
sf4: another FLAC compression format - [https://github.com/cognitone/sf2convert](url).

Others can feel free to add if necessary.

**Comment by KaleidonKep99** [comment]
You have to ask in the Un4seen forums, since they're the owners of the BASS library.

**Comment by shadelegend333** [comment]
BASS already does sf2pack using un4seen's bassflac add-on (in falcosoft midiplayer as an example).  (The others, I'm not sure of.)

Your driver doesn't allow selecting anything with a different suffix than sfpack, sf2, or sfz. If I rename the suffix to one of those and I include bass add-on dlls in the driver folder, it still doesn't work.

I can only conclude that it is something to do with the driver.

**Comment by KaleidonKep99** [comment]
I added support for SF2Pack in the latest release.
For the rest, again, you have to contact Un4seen.

**Comment by shadelegend333** [comment]
Getting BASS_ERROR_CODEC when loading flac encoded .sf2pack with 10.0.0.11.
Doesn't seem to be loading bassflac.dll to decode the samples.

**Comment by KaleidonKep99** [comment]
Try now with .12.

**Comment by shadelegend333** [comment]
.sf2pack functions properly now, thank you.
