### ISSUE TITLE
Deathtrack in DOSBox

### ISSUE THREAD

**Issue by Matthaiks** [KaleidonKep99/OmniMIDI#154]
**Problem**
OmniMIDI makes this [game](https://www.mobygames.com/game/dos/deathtrack) very sluggish.

**Steps to reproduce**
1. Run Deathtrack in DOSBox.

**Expected behavior**
Deathtrack should run as good as with Munt or VirtualMIDISynth.

**Environment**
Windows 10 v1809 x64
OmniMIDI - Version 10a and older
DOSBox 0.74-3

**Comment by KaleidonKep99** [comment]
I found the issue, it'll be fixed in the next preview release.

**Comment by KaleidonKep99** [comment]
Fixed.
