### ISSUE TITLE
Fine tune the volume knob - Not bringing up any windows

### ISSUE THREAD

**Issue by B00ie23** [KaleidonKep99/OmniMIDI#155]
**Problem**
The window for fine tuning the volume knob no longer appears to precisely adjust the volume. Instead, the knob reacts by setting the volume to the cursor's last position before opening the menu to toggle the window.

**Steps to reproduce**
1. Open the Configurator
2. Right-click the volume knob
3. Click "Fine tune the volume knob"
4. No window appears to fine tune the volume level, notice the sudden volume change

**Expected behavior**
Normally a window opens to allow me to set the volume level at a precise value such as 8500 (85%)

**Screenshots/Videos**
![uVlea8Vvx3](https://user-images.githubusercontent.com/45867359/68970594-79eba380-079c-11ea-80f1-6d6ea0bd413a.gif)

**Environment**
 - Operating system: Windows 10 Home
 - CPU: Intel Core i3-6100 @ 3.70 GHz
 - RAM: 16 GB
 - MIDI application: None
 - Version of the driver: 10.0.0.3 (latest)

**Comment by KaleidonKep99** [comment]
Restored in the latest releases.
