### ISSUE TITLE
bug when using sfz

### ISSUE THREAD

**Issue by mutual-sake** [KaleidonKep99/OmniMIDI#156]
**Problem**
when using a sfz(example: KSP, B211, or any other sfz), key 000 does not have any sound while the velocity of that note is 127 and there are samples for 000 for the sfz, also the sfz set key 000 in instrument already

**Steps to reproduce**
1. draw a note at key 000 and 001(for comparison) in any midi editor, set both notes to any audible velocity(127 is recommended, so you can hear 001 clearly), then export that as midi
2. play the midi in any midi player(tested on piano from above, zenith and ultralight midi player)
3. error occurs

**Expected behavior**
when playing that midi on a midi player, you will notice that key 000 does not give sounds but key 001 is loud and clear(you can keep looping that if you think the sfz is still being loaded)

**Screenshots/Videos**
https://youtu.be/Oqh7xVMYits

**Environment**
 - Operating system: Windows 10 Home
 - CPU: i7-8700 @ 3.2Ghz
 - RAM: 8GB
 - MIDI application: Piano From Above 1.1.0
 - Version of the driver: 10.0.0 CR4

**Additional context**
this problem happens everytime, not just for 1 midi or 1 sfz, this problem applies for any midi with notes at key 000 and any sfz that has key 000 set properly

**Comment by KaleidonKep99** [comment]
BASSMIDI seems to be to blame for this. Apparently it ignores any sample set to key 0...
It'll probably take a few days to fix the issue, since Ian usually isn't available on Saturday and Sunday.

I'll get back to you when it's fixed.

**Comment by KaleidonKep99** [comment]
Fixed.
