### ISSUE TITLE
How to add program to blacklist?

### ISSUE THREAD

**Issue by Spherey** [KaleidonKep99/OmniMIDI#157]
I can't add programs to the OmniMIDI blacklist. The instructions say "Add a program to the blacklist by right-clicking it, and selecting "Add executable(s)". To add a name manually, hold SHIFT while clicking "Add executable(s)".", but when I right click on a program in my desktop, it doesn't say "Add executable(s)".

**Steps to reproduce**
Open OmniMIDI Configurator
File -> Blacklist manager
Go to desktop with window open, right click on program, you don't see "Add executable(s)" anywhere

**Expected behavior**
I expected "Add executable(s)" setting to appear

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/57923656/69102524-92b3bd80-0a17-11ea-8ff5-f76dbddbbe9f.png)

**Environment**
 - Operating system: Windows 10 x64
 - CPU: How do I check CPU
 - RAM: 8.00 GB (7.89 GB usable)
 - MIDI application: OmniMIDI (idk which version it doesnt show)
 - Version of the driver:  (how do i check this)

**Additional context**
I'm trying to add VRChat into OmniMIDI Blacklist manager so it doesn't show an error trying to play VR

**Comment by KaleidonKep99** [comment]
To add a program to the blacklist, you need to right-click it, by it meaning the list.
![image](https://user-images.githubusercontent.com/11065274/69141644-7f5f2b80-0ac5-11ea-8931-5c4a0e0c95aa.png)

I'll change the text to be more explanatory in the next release.

**Comment by KaleidonKep99** [comment]
The new blacklist editor available in the latest release.
