### ISSUE TITLE
newest version of omnimidi wont let any program using that

### ISSUE THREAD

**Issue by PianoDude8918** [KaleidonKep99/OmniMIDI#158]
**Problem**
after downloading the newest version of omnimidi, kiva, pfa, and synthesia won\t open

**Steps to reproduce**
1. open program using omni
2. See error

**Expected behavior**
pfa to open normally

**Screenshots/Videos**
cant get a video

**Environment**
 - Operating system: Windows 7 Professional
 - CPU: Intel Core i5-2400
 - RAM: 16GB Ram
 - MIDI application: Piano From Above (Version 1.1.0)
 - Version of the driver: 10.0.0.13

**Additional context**

**Comment by KaleidonKep99** [comment]
I don't have enough information to reproduce the issue.
Please make a video of the issue using a camera or a smartphone.

**Comment by KaleidonKep99** [comment]
Fixed in version [10.0.0.15](https://github.com/KeppySoftware/OmniMIDI/releases/tag/10.0.0.15).
