### ISSUE TITLE
does OmniMIDI/Keppys synthesizer still make the sound not work?

### ISSUE THREAD

**Issue by LexonPlayz** [KaleidonKep99/OmniMIDI#159]
here's the thing.
i was downloading omnimidi/keppys synth, everything was fine with downloading. then after installation, the sound just wasnt working. tried to go to pfa and it showed up but every time i select keppys synth it will always show an error. i quickly tried to found a deletion to make sound working but only found to remove regs. so, is it still the same?

**Comment by KaleidonKep99** [comment]
This is not a valid issue.
Just try it. If it doesn't work, use another synthesizer.

**Comment by LexonPlayz** [comment]
Oh ok

**Comment by LexonPlayz** [comment]
It actually works this time.
