### ISSUE TITLE
Volume meter causes noise when enabled

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#16]
So, I try the new volume monitoring but it's just causes noise when enabled.
If you want proof: https://drive.google.com/open?id=0B-k9O996VHoLSGpYNGcwYUl5T0U

**Comment by KaleidonKep99** [comment]
It works fine for me: https://www.youtube.com/watch?v=TVZMQNLbAmw&feature=youtu.be

I guess your PC is too weak to let BASS process 20ms of data for the volume meters.

**Comment by longnguyen2004** [comment]
Maybe.
P/s: Sometimes it's work, sometimes it doesn't. (??)

**Comment by KaleidonKep99** [comment]
I guess I can close it then.
