### ISSUE TITLE
MIDI programs doesn't open/crashes, when they use OmniMIDI

### ISSUE THREAD

**Issue by DmitrysMusic** [KaleidonKep99/OmniMIDI#160]
**Problem**
This is the same issue as #158 , but with more proofs.

**Steps to reproduce**
1. Depending on a program, just open it, and see, if it's doing something. 
1.1. Some of them (like Tom's MIDI Player) will only crash, after hitting Play button and choosing OmniMIDI.

**Expected behavior**
A program should either open or start playing a MIDI just fine.

**Video, demonstrating the problem**
https://youtu.be/6O8_TaQHIr0

**Environment**
 - Operating system: Windows 10 Pro 1909 build 18363
 - CPU: Intel Core i5-3470
 - RAM: 8 GB
 - MIDI application: Any..?
 - Version of the driver: 10.0.0.13

**Additional context**
No matter if the program was patched or not, this does not resolve the problem.
Reinstalling OmniMIDI from scratch doesn't work as well.

**Comment by KaleidonKep99** [comment]
Can you post the logs from event viewer and from OmniMIDI's debug mode?

**Comment by DmitrysMusic** [comment]
Here are the files.
[event and debug mode logs.zip](https://github.com/KeppySoftware/OmniMIDI/files/3896070/event.and.debug.mode.logs.zip)

**Comment by KaleidonKep99** [comment]
Fixed in version [10.0.0.15](https://github.com/KeppySoftware/OmniMIDI/releases/tag/10.0.0.15).
