### ISSUE TITLE
No possibility of assigning soundfonts to LSB banks

### ISSUE THREAD

**Issue by hakerg** [KaleidonKep99/OmniMIDI#161]
I know that in bass library it's possible to assign banks from soundfonts to a specific LSB bank but there is no such an option in gui

**Comment by KaleidonKep99** [comment]
I'll add it soon.

**Comment by hakerg** [comment]
I managed to fix that but I cannot make a pull request

czw., 26.12.2019, 15:53 użytkownik KaleidonKep99 <notifications@github.com>
napisał:
