### ISSUE TITLE
concert pitching (live playback)

### ISSUE THREAD

**Issue by Kerbinator-Fras** [KaleidonKep99/OmniMIDI#163]
Normally in modern concerts the concert pitch is fixed to 440Hz(A-4)
But recently after reading some articles on the internet I found it's not always right.
Well for example F.F.Chopin's work use 430Hz as A and J.S.Bach use 415Hz.
And in my ear the Rach 3 MIDI feel best compared to Horowitz's 1978 performance in 432Hz.
So it will be highly appreciated to add support for concert pitch in this amazingly fluid synthesizer.
(MIDI Voyager,an Android paid/free app also own this feature while having great performance(much better than PFA/MidiTrail with coolsoft,and only surpassed by Omnimidi)
(Also this can be viewed at pitching CC to all channels,but for some Vocaloid song composed recently I may need to tune it live when playing with a wav file of human voice)

**Comment by KaleidonKep99** [comment]
I'll add this feature on the next release, after the holidays.

**Comment by KaleidonKep99** [comment]
Will be added on 11.1.2.1 or later releases.

**Comment by KaleidonKep99** [comment]
Added to 11.1.3.
