### ISSUE TITLE
How to swap soundfonts list?

### ISSUE THREAD

**Issue by metronomme** [KaleidonKep99/OmniMIDI#164]
Hi, first of all, I love your driver. It works a charm, it's memory efficient and the amount of control it provides is amazing. Thanks!

I was previously using VirtualMidiSynth and I really liked the fact that it provides the option to have several soundfonts on different virtual MIDI ports. I understand that OmniMIDI only provides one MIDI port, which is fine because it has the "Soundfont list" feature; however... I can't seem to be able to swap between lists!!
Currently, the only list that is working is the "Shared list", and no matter how many soundfonts I add to other lists, there's no way I can swap to list 2 or list 3 or anything!

Is there a way to select which soundfont list to use?

Thanks for clarifying!!

Oh, by the way: I'm on Windows 10 x64 version 1903

Thanks!

**Comment by KaleidonKep99** [comment]
Yes, there's a way to switch between SoundFonts!

You can either assign a specific list to an app using the configurator:
![image](https://user-images.githubusercontent.com/11065274/71727430-7e4a4980-2e3a-11ea-94a2-5bf5810c41af.png)
![image](https://user-images.githubusercontent.com/11065274/71727424-78ecff00-2e3a-11ea-8037-352393c6d53b.png)

Or you can use the following hotkeys: ALT+n (n = List number)
![image](https://user-images.githubusercontent.com/11065274/71727465-9a4deb00-2e3a-11ea-853a-bc6a58b2dade.png)

**Comment by KaleidonKep99** [comment]
I'll modify the loading system so that you can tell a specific app to load a custom list, using the configurator.

**Comment by metronomme** [comment]
Thanks!
The hot key is useful, but how should I use it? What app should be active
when pressing alt+number?

Thanks!

**Comment by metronomme** [comment]
Never mind, I found out. It works when the omnimidi config screen is up.
Excellent!
One last question: it seems like the shared list is not responding to hot
keys, or at least there's something not quite right in the way the lists
are loaded... When I load list 3, it seems like list 2 is actually playing.
If I load list 1, nothing changes! Can you please verify that?
Also, can you clarify what's the use of the shared list?

Thanks a lot for your hard work and support!

**Comment by metronomme** [comment]
Ok, I realised now what is happening:
In my setup, when I populate list 2 and I load it using the hotkey alt-2, nothing happens. 
However, if I populate list 3, then it loads when I use the hotkey alt-2! From there on, each hotkey responds correctly, but loading the n-1 list (alt-2 loads list 3; alt-3 loads list 4, etc...)

I have it now set up with my favourite soundfonts on lists Shared, 3 and 4, and I swap between them using alt-1. alt 2 and alt-3

As I said, this is what happens in my set-up, however since I've been messing with it a while, trying to get the lists configured properly, I might have broken something!!
Please let me know if you can reproduce the issue, or otherwise advice on steps to revert to normal, if possible? Thanks again!

Martín

**Comment by KaleidonKep99** [comment]
I'll fix that issue in the next release!

**Comment by KaleidonKep99** [comment]
Fixed in 11.1.2.0.
