### ISSUE TITLE
BEX/BEX64 Error When OmniMIDI.dll is called as non-admin in win7 (again)

### ISSUE THREAD

**Issue by shadelegend333** [KaleidonKep99/OmniMIDI#168]
See Title.

This was previously an issue pre version 9, but fixed.
Now broken again when I updated from 10-point-something to 11.1.3.1.
Still doesn't work after using reinstall from scratch updating to 11.1.4.0.
Crashes OmniMIDI driver and the MIDI player.

Everything works fine if player and OmniMIDI Config is ran as administrator.

**Environment**
 - Operating system: Windows 7 x64 Ultimate
 - CPU: Intel Xeon W3505
 - RAM: 4GB
 - MIDI application: Any
 - Version of the driver: 11.1.4.0

**Comment by KaleidonKep99** [comment]
I need to know the previous release you had before the issue appeared.

**Comment by shadelegend333** [comment]
Nvrm, for some reason the reinstall was glitchy and was still at 11.1.3.1

After the properly updating its fine I guess.
