### ISSUE TITLE
Start sample ramp (Beatnik)

### ISSUE THREAD

**Issue by MXMF55** [KaleidonKep99/OmniMIDI#169]
For imitate Beatnik original DLS softsynth, need disable ramp on startup for use original sample ramp.

For solve this, you can add the new BASS_MIDI_FontInit flag for that:

`#define BASS_MIDI_FONT_NORAMPIN 0x400000`

After enable this, the sound will be same to beatnik

Here:
![Sin título](https://user-images.githubusercontent.com/62956708/78062055-1d101480-735c-11ea-8b34-4fc41a9aeff2.jpg)

i am MIDAPMI

**Comment by MXMF55** [comment]
Thanks for the fix, This is one of various enhances of DLS flag's, originally this features, i talk with ian for more DLS features

**Comment by MXMF55** [comment]
How to enable? i applied the update and not appear any option and ramp still active

**Comment by KaleidonKep99** [comment]
Download the release again.

**Comment by MXMF55** [comment]
Still, no appears any option and no disables the ramp

**Comment by MXMF55** [comment]
xD After 2 reinstalls work well :) topic is a now closed :)
