### ISSUE TITLE
Add option to disable watchdog

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#17]
Please add the option to enable/disable the watchdog in the configurator! It is annoying that I have to switch back to 3.3.1.5 to disable the watchdog while I play MIDIs.

**Comment by KaleidonKep99** [comment]
What's really wrong with the watchdog? Is it doing anything bad?
But ok, I'll add an option to disable it.

**Comment by KaleidonKep99** [comment]
Added option on [version 3.3.1.7](https://github.com/KaleidonKep99/Keppy-s-Driver/releases/tag/3.3.1.7).
