### ISSUE TITLE
OmniMidi ASIO doesent work with PFA

### ISSUE THREAD

**Issue by scttd** [KaleidonKep99/OmniMIDI#170]
![Capture](https://user-images.githubusercontent.com/63203180/78505077-9e89ed00-7736-11ea-91e3-638e8318e95d.PNG)

So I was looking at some of the renderers and I saw ASIO (audio stream input output) and I slelected it because people say its the best renderer, so I tried it and when I launched Piano from above, it gives me that error. (I put the picture on top)

btw and I do have asio installed, but the weird thing is when I already have it open and then slect ASIO it does work which is weird so yeah

if anyone can help me, that would be great.

**Comment by minelolpride** [comment]
can't seem to get anything similar here, I installed [ASIO4ALL](http://www.asio4all.org/), switched OmniMIDI to use ASIO then restarted all programs using OmniMIDI and it worked. What ASIO did you install or are trying to use?

**Comment by scttd** [comment]
Nevermind, fixed it I saw a closed post or something. Thanks for trying to help me though
