### ISSUE TITLE
Clicking on Note Events (first init per session only)

### ISSUE THREAD

**Issue by B00ie23** [KaleidonKep99/OmniMIDI#171]
**Problem**
Normally clicking sounds can be heard if the voice count is capped, as OM states under Disable Fade-Out. This is not the case when playing lighter MIDIs, as the click occurs on _every_ note event, even on a lone note.

**Steps to reproduce**
1. Enable any quiet SoundFont
2. Play any MIDI on any application
3. Clicking is/should be audible

**Screenshots/Videos**
[Video Source (.zip)](https://github.com/KeppySoftware/OmniMIDI/files/4496048/video.zip)
_(I switched from KDMAPI to Pre-Rendered and back in the clip)_

**Environment**
 - Operating system: Windows 10 Home -  Build 18363
 - CPU: Intel Core i3-6100 @ 3.70 GHz
 - RAM: 16 GB
 - MIDI application: _(any)_
 - Version of the driver: 11.2.0.0

**Additional context**
I did some further examinations in Kiva at the time of writing this, and only does the click go away when you switch the audio to Pre-Rendered and back, thus first init per session.
I also noticed that the clicking is more audible on more quieter SoundFonts, especially on lower notes.

**Comment by KaleidonKep99** [comment]
This might be an issue caused by an update requested by another user in issue #169.
I'll make it as an opt-in option in the configurator.

**Comment by KaleidonKep99** [comment]
Added as an option in the configurator.
