### ISSUE TITLE
Cannot Fix OmniMidi

### ISSUE THREAD

**Issue by javaarchive** [KaleidonKep99/OmniMIDI#172]
**Problem**
Any application using OmniMidi's midi output or KDMAPI dies. 

**Steps to reproduce**
1. Install OmniMidi from nonadmin account but use admin password
2. Close out of the configurator that's run from admin
3. Open the configurator again this time it's in nonadmin mode
4. Add any soundfont
5. Use any application and set it's input to OmniMidi or make it use KDMAPI
6. Application crashes with unrecongnizable exit code
**Expected behavior**
The application to work

**Screenshots/Videos**
Embers dies when I play a midi with the output OmniMidi but not with the microsoft wavetable gs
Same with UMP when I choose the name of a weird lettered output
Switching to KDMAPI on kiva makes it die
Zenith dies on startup
**Environment**
 - Operating system: Windows 10
 - CPU: See image
 - RAM: 16gb
 - MIDI application: See above (Version x.x.x.x)
 - Version of the driver: 11.2
![image](https://user-images.githubusercontent.com/20248577/79697791-9f904380-8239-11ea-9049-b7a9bc1d8661.png)

**Additional context**
I reinstalled OmniMidi and the error box spam I got previously stopped

**Comment by lewisakura** [comment]
I have determined the cause of both of our issues.

OmniMIDI no longer works in non-admin environments. Try running your applications as admin (making sure to add a soundfont in the admin configurator) and you should be able to see that it works perfectly fine.

**Comment by javaarchive** [comment]
Thank you, it was probaly too time consuming to test on different accounts.
