### ISSUE TITLE
Default Blacklist missing

### ISSUE THREAD

**Issue by lewisakura** [KaleidonKep99/OmniMIDI#173]
**Problem**
Every time I start FiveM, I get a blacklist error. After reinstalling OmniMIDI from scratch (both with the configurator and manually) it still reports this error. Other applications will either report this error or just crash immediately (à la #172).

**Steps to reproduce**
- Run application in non-elevated environment.

**Expected behavior**
The applications would start normally and OmniMIDI would function correctly, using my soundfonts to produce audio.

**Screenshots/Videos**
![](https://pantsu.review/5Yo3q2Y.png)

**Environment**
 - Operating system: Windows 10 Pro Version 1909 (64-bit) Release 18363, Revision 720
 - CPU: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
 - RAM: 16GB
 - MIDI application: FiveM (Version 2369)
 - Version of the driver: 11.2.0

**Additional context**
FiveM is a GTA5 mod that uses a MIDI driver to play audio in certain cases, most notably the main menu.

**Comment by javaarchive** [comment]
I'm curious, I haven't tried this yet, but have you tried updating your .NET framework. I think that's the cause of my issue and I'm waiting to test it this Saturday

**Comment by lewisakura** [comment]
I'm on latest.

**Comment by KaleidonKep99** [comment]
I don't know if you're still using OmniMIDI, but you could try redownloading the blacklist from the configurator.
![image](https://user-images.githubusercontent.com/11065274/107986218-e5d64080-6fcb-11eb-8e49-e7df9b647230.png)
