### ISSUE TITLE
No compilation guide, no build with Windows 10 2004+ fix.

### ISSUE THREAD

**Issue by Danfun64** [KaleidonKep99/OmniMIDI#174]
I'm running Windows 10 20H2. I just noticed the "Windows 10 2004+ fix" commit and wanted to compile OmniMIDI myself since there didn't seem to be any builds of it. However, there's no compilation guide. It's not clear how the software is supposed to be signed. The "CompileExes.bat" file references Inno Setup 5 instead of Inno Setup 6, as well as two files that aren't noticeable from a clean git clone. There's also no root directory ".sln" or related project files. If a guide showing the order everything is supposed to be run could be made, it would be really helpful. Having an official build with the Windows 10 2004+ fix would also be nice.

**Comment by KaleidonKep99** [comment]
It has been fixed in OM12+.
