### ISSUE TITLE
Driver keeps unregistering itself

### ISSUE THREAD

**Issue by blulere** [KaleidonKep99/OmniMIDI#178]
**Problem**
When idle for an extremely long time, OmniMIDI will unregister both of it's drivers causing PFA to default to GS Wavetable Synth (and very rarely, VMS)

**Steps to reproduce**
1. Open OmniMIDI, where it prompts you to register the drivers.
2. Wait some time (from my observations, around 10-20 minutes?)
3.  Sound no longer plays through PFA.
4. Re-open PFA.
5. It defaults to GS Wavetable Synth and sounds horrible as usual.

**Expected behavior**
1. Open OmniMIDI, greeted with the soundfont selection list.
2. Wait some time.
3. PFA works normally.
4. Re-open PFA.
5. PFA defaults to OmniMIDI and sounds amazing as usual.

**Screenshots/Videos**
Fallback on VMS (never happened before), OmniMIDI unregistered
![image](https://user-images.githubusercontent.com/40177441/107884771-b43b7780-6eee-11eb-9cca-983a9d302a9e.png)
Prompt 1
![image](https://user-images.githubusercontent.com/40177441/107884810-d6cd9080-6eee-11eb-9ea5-e45cb7507e69.png)
Prompt 2
![image](https://user-images.githubusercontent.com/40177441/107884817-e0ef8f00-6eee-11eb-8fd6-6d81b8eadd9b.png)

**Environment**
 - Operating system: Windows 10 20H2
 - CPU: Intel Core i5-2520m
 - RAM: 4GB DDR3 RAM
 - MIDI application: Piano From Above 1.1.0 (but generally happens for all)
 - Version of the driver: 11.2.0.0

**Additional context**
Also happens on startup.

**Comment by KaleidonKep99** [comment]
This issue is a duplicate of issue #174.
It has been fixed in OM12+.

**Comment by blulere** [comment]
Ok, weird, this is happening again on latest, but now instead of it happening when I wait a while, it happens after closing the GUI.

I'm on Windows 8.1 now, if that helps anything. This also happened on Windows 7.
The only things that really have changed is that opening any application that makes use of OmniMIDI gives two errors when I open them: 
![image](https://user-images.githubusercontent.com/40177441/108715676-1a3d8580-7513-11eb-9d1a-a364aa98b09d.png)
![image](https://user-images.githubusercontent.com/40177441/108715724-23c6ed80-7513-11eb-9aff-1f94eddac637.png)
The app loads normally after this.
Registering the driver says this: 
![image](https://user-images.githubusercontent.com/40177441/108715845-478a3380-7513-11eb-9f51-cca8abebb6d2.png)
...but a restart changes nothing.
I'm also still getting the registration issues.

**Comment by KaleidonKep99** [comment]
Make sure that raw mode is disabled in the advanced WASAPI settings. You can access them by clicking the "Change output" button next to the engine selector.
![image](https://user-images.githubusercontent.com/11065274/108720531-3b0cd780-7521-11eb-9edc-fb88bfed94df.png)

**Comment by blulere** [comment]
Raw mode was already disabled.
Also, a new issue has occured; OmniMIDI is only complaining about the x86 version of the driver being uninstalled, instead of both.
For a while, the driver wasn't even recognised as a MIDI output, but a reinstall fixed this issue.
If it helps, here are my settings: 
![image](https://user-images.githubusercontent.com/40177441/108778679-a1175000-755d-11eb-8021-b39542fe050b.png)
![image](https://user-images.githubusercontent.com/40177441/108778700-ad031200-755d-11eb-82eb-6b054876dfff.png)

**Comment by KaleidonKep99** [comment]
I'll create a Windows 8.1 VM and test it there.

**Comment by KaleidonKep99** [comment]
Fixed in 13.5.2.
