### ISSUE TITLE
OmniMIDI 13.8 Does not work with Cheat Engine

### ISSUE THREAD

**Issue by Lucas9810** [KaleidonKep99/OmniMIDI#182]
Using the speedhack on Piano From Above, no changes are made to the speed on the player.
Video: https://www.youtube.com/watch?v=1hzn2-e8sJw

OmniMIDI 13.8
Piano From Above 1.1.0 x64
Windows 10 20H2

**Comment by KaleidonKep99** [comment]
This bug appeared after i fixed an issue in WinMMWRP.
I'll look into it.
