### ISSUE TITLE
Omnimidi Continue crashing midi players 

### ISSUE THREAD

**Issue by Daniel-176** [KaleidonKep99/OmniMIDI#184]
**Problem**
Omnimidi Crashing midi player when i try to opan midi

**Steps to reproduce**
1. Play MIDI xxx.mid on application UMP

**Screenshots/Videos**
The same problem than this https://www.youtube.com/watch?v=e0dP2kArU_0

**Environment**
 - Operating system: Windows 10 Pro
 - CPU: AMD Athlon II X2
 - GPU: AMD Radeon R7 240
 - RAM: 8GB
 - MIDI application: Ultralight Midi Player
 - Version of the driver: Latest OmniMIDI

**Comment by KaleidonKep99** [comment]
11.2 is really old.

**Comment by Daniel-176** [comment]
yea but. when you or anyone will fix this?

**Comment by WarpPrime** [comment]
It seems like I am having the same problem as well. Any fixes?

**Comment by Daniel-176** [comment]
This Issue Will be Closed if Want to open ask me
