### ISSUE TITLE
OmniMIDI crashes PFA when output mode is set to OmniMIDI

### ISSUE THREAD

**Issue by WarpPrime** [KaleidonKep99/OmniMIDI#185]
**Problem**
OmniMIDI crashes PFA when output mode is set to OmniMIDI.

**Steps to reproduce**
1. Play any MIDI file on Piano From Above (PFA-1.1.exe)
2. Go to Preferences > Audio
3. Click MIDI output device > OmniMIDI

**Expected behavior**
PFA freezes, then crashes (closes out) moments later

**Environment**
 - Operating system: Windows 10
 - CPU: 3 GHz
 - RAM: 8 GB
 - MIDI application: Piano From Above 1.1
 - Version of the driver: 13.8.2.0

**Comment by KaleidonKep99** [comment]
I will try to fix the issue once I have my PC back up and running again.
Right now I can't access the source code, nor I have access to a PC that can run Visual Studio.

**Comment by KaleidonKep99** [comment]
I can't reproduce the issue, since there's not enough info in the report.

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
