### ISSUE TITLE
Synthesizer device not listed

### ISSUE THREAD

**Issue by mitterdoo** [KaleidonKep99/OmniMIDI#187]
**Problem**
The OmniMIDI device does not appear in any MIDI out device lists (have tried FL Studio and PFA)

**Steps to reproduce**
1. Install OmniMIDI from scratch
2. Restart PC
3. Open FL Studio or PFA
4. Reconfigure MIDI out
5. Notice that OmniMIDI is not listed

**Expected behavior**
The MIDI device clearly should be listed, even *after* using **Extensions > OmniMIDI Register Tool > Register the driver** and restarting my PC.

**Screenshots/Videos**
![FL Studio](https://user-images.githubusercontent.com/4317493/118062056-0869c280-b34b-11eb-9770-1dc896d07b37.png)
![PFA](https://user-images.githubusercontent.com/4317493/118062089-19b2cf00-b34b-11eb-8f1f-ff4df0ba9fd6.png)

**Environment**
 - Operating system: Windows 10 Home (10.0.19042.928 AMD64)
 - CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (AMD64 architecture)
 - RAM: 16257MB (17.047.015.424 bytes)
 - MIDI application: FL Studio v12.5 build 59
 - MIDI application: Piano From Above v1.1.0
 - Version of the driver: 13.8.2.0

**Extra comments**
I've already attempted:
* Registering the driver and restarting
* Unregistering and re-registering the driver, then restarting
* Using the "Reinstall OmniMIDI from scratch" tool, then restarting
* Using the "Delete OmniMIDI's user data" tool, reinstalling and restarting (the program still had all my soundfonts listed..wondering if it even deleted any data)

None of these actions have fixed the problem.

**Comment by mitterdoo** [comment]
I had forgotten that for certain applications that weren't built with the driver in mind, you must patch their executables with the Windows Multimedia Wrapper. Doing this left a working OmniMIDI port in my DAW, fixing the issue.
My most sincere apologies for overlooking this step. I'll go ahead and close this issue

**Comment by KaleidonKep99** [comment]
Actually, it should be shown under the WinMM devices anyway, so this is a serious issue.

I'll look into it once I have a working computer. for now I'll just leave the issue open.

**Comment by KaleidonKep99** [comment]
I might have fixed the issue in version 14.x.
You could please try the latest version and see if it works?

**Comment by mitterdoo** [comment]
Sadly that didn't fix the problem. I still had to patch my DAW's executable manually, which still left OmniMIDI's port listed as the only input in my device list.

**Comment by KaleidonKep99** [comment]
Could you please re-install OmniMIDI from the configurator using the "Reinstall OmniMIDI with default settings" option, under "Tools", and see if that fixes the issue?
It might be an issue with the mask system, which I will definitely remove in version 14.6 since no one uses it anyway.

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
