### ISSUE TITLE
Can someone tell me why Windows insists on unregistering Midi Drivers?

### ISSUE THREAD

**Issue by Zimond47** [KaleidonKep99/OmniMIDI#188]
Sorry that I missuse this for asking that, But it just baffles me that I cannot find a permanent solution to this. I am using Omni Midi for High Quality Soundfonts and an OPL emulation driver for retro sound. Both need to be re registered everytime before I wanna use them. Is there really no way around this? I mean, I am aware that Midi files are ranking quite low in priority nowadays but there must be a way to stop WIndows 10 from unregistering them all the time.

**Comment by minelolpride** [comment]
You haven't posted what version of the driver you are running... Have you updated recently at all? [This release](https://github.com/KeppySoftware/OmniMIDI/releases/tag/12.0.0.0) fixed the issue of the driver getting unregistered from 20Hx versions of W10. Just note that you will have to restart after passing by this version.

**Comment by KaleidonKep99** [comment]
> 
> 
> Sorry that I missuse this for asking that, But it just baffles me that I cannot find a permanent solution to this. I am using Omni Midi for High Quality Soundfonts and an OPL emulation driver for retro sound. Both need to be re registered everytime before I wanna use them. Is there really no way around this? I mean, I am aware that Midi files are ranking quite low in priority nowadays but there must be a way to stop WIndows 10 from unregistering them all the time.

I fixed the issue in the latest updates, by making OM talk with Windows' PnP system.
This change has been put in place by Microsoft because drivers kept messing around with the Drivers32 registry key, which is not good behavior.

**Comment by Zimond47** [comment]
Oh, thank you. No I havent checked the newest version or course.. sorry that was a Rookie mistake. Thought it was something WIndows specific since it happened to any midi driver I tried to use not just Omni Midi. It seems to be stable now :) At least Omni Midi.

**Comment by KaleidonKep99** [comment]
Closed.
