### ISSUE TITLE
Timidity++ Recommendations

### ISSUE THREAD

**Issue by MXMF55** [KaleidonKep99/OmniMIDI#189]
Hello, ¿can you improve or make a fluidsynth driver or timidity for windows instead bassmidi? Bassmidi have seriously poor perfomance with all system and notes doesn't stop when need it. Example for low end computers. Omnimidi have also a gritched on perfomance configurator windows also and when if you load sometimes the cpu the sound fails or skip audio when record directly to wav, This problem  not appears with fluidsynth/timidity++. Shakra maybe?.

It's stranger but my cpu load 100% when move the Omnimidi configuration interface, but during playing never exceeds than 20% cpu and the audio doesn't play between realtime and skipped or delayed start of sample sound.

Microsoft GS doesn't skip or any lagg but cut notes due voices reduction.

**Comment by KaleidonKep99** [comment]
Shakra will allow developers to use custom engines for playback.
