### ISSUE TITLE
Disabling one soundfont causes all soundfonts or the driver itself not to play any MIDI's

### ISSUE THREAD

**Issue by FreeJusticeHere** [KaleidonKep99/OmniMIDI#19]
Sorry if I'm wasting time, but I really need to get this working, because CoolSoft and BASSMIDI just don't have all that I need.

**Comment by KaleidonKep99** [comment]
I'll try fix the problem.

**Comment by FreeJusticeHere** [comment]
Thank you!

**Comment by KaleidonKep99** [comment]
Fixed as of [version 3.3.2.0](https://github.com/KaleidonKep99/Keppy-s-Driver/releases/tag/3.3.2.0).
