### ISSUE TITLE
Programs using OmniMidi not making sound

### ISSUE THREAD

**Issue by RomanticFalconXL** [KaleidonKep99/OmniMIDI#190]
**Problem**
The programs that use OmniMidi are not making sound. Loading other soundfonts/updating the application/registering the driver/starting as administrator doesn't work. I did not change any settings prior to this error.

**Steps to reproduce**
Open a program that uses OmniMIDI (such as PFA, Chikara, FL Studio) and try to play something

**Expected behavior**
I would normally expect PFA/Chikara, etc. to play something when I loaded MIDIs/placed notes in them

**Environment**
 - Windows 10 Version 2009
 - CPU: i7-8750h
 - RAM: 16 GB
 - MIDI application: PFA, Chikara, and other programs that use OmniMidi
 - Version of the driver: OmniMIDI 13.8.2

How do I make OmniMIDI play sound again? Answers are appreciated

**Comment by minelolpride** [comment]
Theres quite a few things that would lead to this issue but we can check a couple things in OmniMIDI.

Consider the following image of the settings
![omc](https://user-images.githubusercontent.com/16008698/119266187-09022480-bba7-11eb-9028-54c211c6f6f6.png)

- (Red circle) Check to see if your audio engine and output device selections actually work. Most likely it's the output device selected, so click 'Change output' and change the 'Current output' around. If it's not set to your normal output device, changing it back should restore your audio.
- (Blue circle) Check that the Volume didnt get set to 0 or something.
- (Green circle) I hope this didn't get enabled by accident. If this is ticked, untick it.
- (Purple circle) I mean, if this is causing the issue we could find out by disabling this.

**Comment by KaleidonKep99** [comment]
Thank you minelolpride for the help!

You should also check the buffer size, since sometimes that can also make the audio go missing because of buffer underruns.

**Comment by KaleidonKep99** [comment]
Oops accidentally closed.

**Comment by KaleidonKep99** [comment]
Closed for inactivity.

**Comment by xp2-882030kgz010602** [comment]
I know it's been over two years, but I'm having this exact same issue. I've already tried all the things in this post without success. I don't know what else could be causing the issue, as I've tried patching PFA as well.

> Theres quite a few things that would lead to this issue but we can check a couple things in OmniMIDI.
> 
> Consider the following image of the settings ![omc](https://user-images.githubusercontent.com/16008698/119266187-09022480-bba7-11eb-9028-54c211c6f6f6.png)
> 
> * (Red circle) Check to see if your audio engine and output device selections actually work. Most likely it's the output device selected, so click 'Change output' and change the 'Current output' around. If it's not set to your normal output device, changing it back should restore your audio.
> * (Blue circle) Check that the Volume didnt get set to 0 or something.
> * (Green circle) I hope this didn't get enabled by accident. If this is ticked, untick it.
> * (Purple circle) I mean, if this is causing the issue we could find out by disabling this.
