### ISSUE TITLE
Audio Output 

### ISSUE THREAD

**Issue by ar06x** [KaleidonKep99/OmniMIDI#193]
Omnimidi refuses to output any audio to a VB Audio cable.

**Comment by ar06x** [comment]
Nvm, turns out windows needs a minimum of volume 1 for some weird reason (No, not in omnimidi)

**Comment by KaleidonKep99** [comment]
Oh. Okay.

**Comment by wolfy01** [comment]
Reopening issue because omnimidi is actually outputting to system audio (If that makes sense?) instead of what I set it to (VB Audio Cable)
