### ISSUE TITLE
Thank you for new updates!

### ISSUE THREAD

**Issue by asigalov61** [KaleidonKep99/OmniMIDI#194]
@KaleidonKep99 Just wanted to thank you for your great work and for the latest updates. Now it works even better than before! :)

Please continue the development/support because OmniMIDI is a very needed and much-appreciated software. 

Sincerely,

Alex

**Comment by KaleidonKep99** [comment]
Thank you! I'll do my best to keep this driver running for as long as possible.
I'm also working on an extension for it called Shakra, which will solve some more issues that can't be fixed because of OmniMIDI's internal limitations!

**Comment by asigalov61** [comment]
@KaleidonKep99 Yes, thank you. I checked it out and it is definitely a great idea. I will keep an eye on Shakra dev and will be happy to beta-test :)

Otherwise, thank you again. :)

Alex
