### ISSUE TITLE
Anything that connects to omnimidi crashes

### ISSUE THREAD

**Issue by ar06x** [KaleidonKep99/OmniMIDI#195]
Including Kiva or any MIDI player. Also has the same effect on every browser I have (Edge, Brave, and Chrome)

**Comment by ar06x** [comment]
Started happening after I updated to the latest version of omnimidi. I unregistered, and re-registered omnimidi, and restarted windows, but that still had no effect

**Comment by ar06x** [comment]
Even attempted to un-install and re-install omnimidi. 

EDIT: Only solution I've found is to downgrade to OmniMIDI - Version 14.4 which will fix the issue

**Comment by KaleidonKep99** [comment]
Fixed in version [14.5.1.0](https://github.com/KeppySoftware/OmniMIDI/releases/tag/14.5.1.0).
