### ISSUE TITLE
because of omnimidi's multimedia wrapper, piano from above, and synthesia 0.8.0 won't slow down using cheat engine.

### ISSUE THREAD

**Issue by Atekuro95** [KaleidonKep99/OmniMIDI#196]
a year ago, the multimedia wrapper patch is on piano from above, it's able to slow down using cheat engine, except synthesia 0.8.0. but then, today, with the multimedia wrapper patch on, none of the programs like piano from above, and synthesia 0.8.0 won't slow down using cheat engine, no matter what speed I put in.

![image](https://user-images.githubusercontent.com/22590518/124182436-3c30b100-da8d-11eb-94e0-89f3cb0c9708.png)

**Comment by KaleidonKep99** [comment]
Enable this option in the configurator.

![image](https://user-images.githubusercontent.com/11065274/124200992-0fa18700-dad7-11eb-8ea3-f3681ce2b1cb.png)

**Comment by KaleidonKep99** [comment]
Closed for inactivity.

**Comment by LexonBlackzz** [comment]
While using the latest version of OmniMIDI, not even the built in speed hack works in PFA.

**Comment by KaleidonKep99** [comment]
> While using the latest version of OmniMIDI, not even the built in speed hack works in PFA.

I seem to be unable to reproduce the issue, because checking the WinMM function in the configurator makes the speed hack work in PFA through Cheat Engine.
The speed slider in PFA is unaffected by the function, since it internally calculates how fast/slow the MIDI should be played at.
