### ISSUE TITLE
Issues with noteoff delay and dithering.

### ISSUE THREAD

**Issue by MXMF55** [KaleidonKep99/OmniMIDI#197]
most midis, by default that not contains noteoff this option doesn't work properly, needs adds noteoff events manually.

..and solves partially due if you look one note that the lenght is less than value (in ms) that you set, this will skip the last note (Overlapping). The overlapped need send stop message to the note and notes need shutdown a 10 ms after stop message.

Currently to get working properly need enable "only kill last note on as noteoff" option enabled and will gets random notes shutdown during playback of some 128bpm and Piano chords.

This is the more easily to explain. 

Second, about of dithering the sound always looks near to nearest eightboor. Test it personally with midiplayer (falcosoft).

**Comment by KaleidonKep99** [comment]
I updated the BASS libraries in the latest canary release.
You could give it a try now.

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
