### ISSUE TITLE
OmniMidi and WinMM patched apps don't open.

### ISSUE THREAD

**Issue by PiggyPig123** [KaleidonKep99/OmniMIDI#198]
When OmniMIDI is launched, it crashes due to an unhanded exception.
Some WinMM patched apps crash as OmniMIDI.dll fails.

**Steps to reproduce OmniMIDI crashing**
1. Run OmniMIDIConfiguator.exe

**Steps to reproduce WinMM patched apps crashing**
1. Open a WinMM patched app.

What I expected to happen was OmniMIDI and WinMM patched apps to start.

**Screenshots/Videos**
WinMM patched domino crash details in event viewer.
![image](https://user-images.githubusercontent.com/22107529/125358886-86404f00-e337-11eb-868a-cdcbe6d46f4c.png)
OmniMIDI crash details in event viewer.
![image](https://user-images.githubusercontent.com/22107529/125359231-fb138900-e337-11eb-820e-f0fddec4fc7a.png)

**Environment**
 - Operating system: Microsoft Windows 10 Pro Build 19403
 - CPU: Intel Core i7 @3.33GHz
 - RAM: 24GB
 - MIDI application: Domino.exe (Version 1.43.3.0)
 - Version of the driver: 14.6.0.50
 
**Additional context**
When javaw.exe is patched, UMP runs fine whereas minecraft crashes.

**Comment by KaleidonKep99** [comment]
Test .52 and let me know if that has the issue as well.

I also need the debug log from the configurator, but apparently you're unable to open it...
It doesn't do any XML related tasks, so I don't know where that XML error is coming from...

**Comment by PiggyPig123** [comment]
.52 didn't work ether, but I figured out that opening OmniMIDIMixerWindow does this: 
![image](https://user-images.githubusercontent.com/22107529/125376544-3a060680-e359-11eb-8661-3a2cbbbcd737.png)

OmniMIDIDebugWindow does something similar.
<img width="1273" alt="Screenshot (2)" src="https://user-images.githubusercontent.com/22107529/125377090-5a829080-e35a-11eb-8522-f39747f4c389.png">

**Comment by KaleidonKep99** [comment]
Please run the configurator through the command prompt using the /rei argument.
```batch
C:\Windows\SysWOW64\OmniMIDI> OmniMIDIConfigurator.exe /rei
```

**Comment by PiggyPig123** [comment]
Done, didn't help.

**Comment by KaleidonKep99** [comment]
I've added a troubleshooting system to the configurator, you could try and see if that fixes it.

**Comment by PiggyPig123** [comment]
Does the troubleshooting system start when the configurator it launched, as if so, it didn't work.

**Comment by KaleidonKep99** [comment]
> 
> 
> Does the troubleshooting system start when the configurator it launched, as if so, it didn't work.

That is really weird.
I added the troubleshooter to the pre-boot environment of the configurator.
Try running it through the command prompt with the following parameters:
`OmniMIDIConfigurator.exe /troubleshoot`

**Comment by PiggyPig123** [comment]
Nothing, Still doesn't launch.
![image](https://user-images.githubusercontent.com/22107529/127326195-3a59bb09-eda1-470d-b10c-b009c0a23839.png)

Also, I've tried using older versions of OmniMidi (pre 14.6) and had no luck.

**Comment by KaleidonKep99** [comment]
Yeah I've been trying to reproduce the same behavior for a while and I still can't manage to do it...

**Comment by PiggyPig123** [comment]
I tried 14.6.5 and all winmm patched apps give a error message now.
![image](https://user-images.githubusercontent.com/22107529/128617143-15640710-f49a-4f1c-af9c-5a760c4265b6.png)

**Comment by KaleidonKep99** [comment]
Yeah you seem to be stuck in a loop where the configurator tries to initialize to create the registry keys, but fails because some weird .NET issue with XML settings (which are used by the configurator itself to store some internal configs) causes it to crash.

This also causes the driver to crash on start-up because the required registry keys are not available.

**Comment by KaleidonKep99** [comment]
Try this version, it might fix the issue: https://github.com/KeppySoftware/OmniMIDI/releases/tag/14.6.6.0

**Comment by PiggyPig123** [comment]
It worked. :)
