### ISSUE TITLE
XAudio crashing applications + Throwing illegal operation

### ISSUE THREAD

**Issue by B00ie23** [KaleidonKep99/OmniMIDI#199]
**Problem:**
XAudio is behaving strange, it'll randomly crash any application currently using the driver, usually while live-tinkering settings.
It's also throwing an illegal operation error when this happens.

**Steps to reproduce:**
_(Note: These steps may not be consistent, as this is random)_
1. Open any MIDI application (TMIDI, Kiva, PFA, etc...)
2. Open an audio stream using the XAudio engine
3. With live settings active, try adjusting either active SoundFont, or advanced settings until it throws the error/crashes
4. If logs are enabled, the error should appear, otherwise the app immediately crashes.

**Expected behavior:**
I was expecting to hear a live preview of some adjustments to samples per frame (SPF) while experimenting with the advanced settings.

**Error screenshots:**
_(Error message 1)_
![TMIDI64_VLeDeeVjhj](https://user-images.githubusercontent.com/45867359/125565924-0a96512f-394f-4f88-9b54-8f1e264555d0.png)
_(Error message 2)_
![TMIDI64_jJBBBkjYqB](https://user-images.githubusercontent.com/45867359/125565985-34fd863c-d6d8-4c71-b3af-3a38bfb496a2.png)

**System environment:**
 - Operating system: Windows 10 Home Edition (21H1)
 - CPU: Ryzen 5 3600
 - RAM: 16 GB
 - MIDI application: TMIDI _(debug log attached at the very bottom)_
 - Version of the driver: 14.6.0.52

**Additional context:**
I wanted to try XAudio since it is working, and that DirectX Audio is capped at 80 SPF (or equivilant to WASAPI.)
I also thought there was something wrong with my registry, so I clean reinstalled the driver. Turns out that wasn't the case, although the crashing is less but still frequent.

Here's the log file for TMIDI while attempting to replicate steps for the error message.
[TMIDI64.exe (Debug output).txt](https://github.com/KeppySoftware/OmniMIDI/files/6813719/TMIDI64.exe.Debug.output.txt)

_(Edit: Corrected XAudio name; 2.9 is the version number, my bad)_

**Comment by KaleidonKep99** [comment]
Fixed in version .55.

**Comment by B00ie23** [comment]
Unfortunately this is still causing crashes. I tried a reboot and attempted to play something small and it threw the same error as soon as the audio stream started.
![U5Hf7ah86X](https://user-images.githubusercontent.com/45867359/125736026-71ca2ac0-6e9b-4044-a218-fac64fcb819a.gif)

**Comment by KaleidonKep99** [comment]
Oops by fixing the issue I created another one! 😨 
I'll fix it asap.

**Comment by KaleidonKep99** [comment]
It should work properly now! [14.6.0.67](https://github.com/KeppySoftware/OmniMIDI/releases/tag/14.6.0.67)

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
