### ISSUE TITLE
All notes have same volume, even if they are set to play softer

### ISSUE THREAD

**Issue by FreeJusticeHere** [KaleidonKep99/OmniMIDI#20]

**Comment by KaleidonKep99** [comment]
Fixing that already! :P

**Comment by KaleidonKep99** [comment]
Fixing that already!
It's actually a problem I noticed 2-3 hours ago, with a MIDI that has numerous MIDI tracks volume changes.

The mixer overrides these events.

I'll push a fix soon! Stay tuned.

**Comment by FreeJusticeHere** [comment]
Oh, sweet! Thanks!

**Comment by KaleidonKep99** [comment]
Fixed! [Here.](https://github.com/KaleidonKep99/Keppy-s-Driver/releases/tag/3.3.2.1)

**Comment by FreeJusticeHere** [comment]
Thank you!
