### ISSUE TITLE
A struggle of OmniMIDI/KDMAPi VS Windows 11

### ISSUE THREAD

**Issue by ghost** [KaleidonKep99/OmniMIDI#202]
**Problem**
A KDMAPi Initialization error occurs for every time FL Studio is launched.
Additionally, every time I open the configurator for OmniMIDI this shows up.
![image](https://user-images.githubusercontent.com/36340655/129283852-343e8267-5c56-4b41-85a0-a0b18e00d13c.png)

**Steps to reproduce**
Error 1: Launch FL Studio.
Error 2: Launch OmniMIDI on Windows 11's Insider Build.
**Expected behavior**
Error 1: FL Studio runs like normal and allows me to produce music that I need to get finished soon.
Error 2: OmniMIDI Actually fixes the driver issue and then a reboot of my system should let me just go to the Soundfonts screen.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

https://user-images.githubusercontent.com/36340655/129284588-0ec45693-feec-4835-9ac3-f4292ad2f88b.mp4

https://user-images.githubusercontent.com/36340655/129284595-8e856ff9-067e-499f-8cc1-0216fccbd698.mp4

**Environment**
 - Operating system: Windows 11 version 10.0.22000 Build 22000
 - CPU: Ryzen 9 3900 (12 core)
 - RAM: 32GB
 - MIDI application: FL Studio, OmniMIDI
 - Version of the driver: 14.6.6

**Additional context**
I will when I've identified what you need to know.

**Comment by ghost** [comment]
THIS ISSUE HAS FIXED ITSELF, I USED THE WRONG PATCH METHOD FOR MY DAW AND IT BROKE EVERYTHING.

I have since been able to reach the repatch button and use the right patch for FL Studio and now it *seems* to be working as intended. i will return with an update if the program is still bugging out.

**Comment by ghost** [comment]
New Update: Everything that Relies on KDMAPi has been swapped and patched into WMW. OmniMIDI still cannot get a hold on a Midi Driver spot as Midi9 is overtaken by what appears to be my headset drivers.

**Comment by KaleidonKep99** [comment]
I updated the PnP system in 14.6.7 to actually check for the availability of the slots through Windows' PnP registry keys, instead of relying on the Drivers32 key.
Let me know if that fixes it.

**Comment by ghost** [comment]
This has not helped. I just installed 14.6.9 and this error still exists
![image](https://user-images.githubusercontent.com/36340655/130319786-c9c7e943-b5ee-48c0-9cc3-3a89c3ba9d68.png)
though, it can be ignored, some things in FL request OmniMIDI to be alive when it can't be.
Upon opening Fruity LSD for example, this shows up
![image](https://user-images.githubusercontent.com/36340655/130319835-145fc192-7346-48e1-9624-c59cc0c3d2d8.png)

**Comment by KaleidonKep99** [comment]
I could make OmniMapper use OmniMIDI through KDMAPI when selected.
The fact that you ran out of slots makes me think that there are too many software synthesizers/dummy devices taking ahold of them.

**Comment by KaleidonKep99** [comment]
One year later... It should work on the latest PR, let me know... (Sorry for being so late oops)
