### ISSUE TITLE
An error occurs when switching different soundfonts.

### ISSUE THREAD

**Issue by FoxyBuddy** [KaleidonKep99/OmniMIDI#203]
**Problem**
An error occurs when switching different soundfonts. Especially on large MIDIs.

**Steps to reproduce**
1. Play any MIDI on a MIDI player. Then I choose a different soundfont.
2. The driver throw an error in function "EventProcesser".

**Expected behavior**
The sound will be changed correctly without any error.

**Screenshots/Videos**
![2021-08-17](https://user-images.githubusercontent.com/20873762/129676884-4e3bcb26-e407-4188-a220-602f8ccc92b1.png)

**Environment**
 - Operating system: Windows 10 Professional 20H2
 - CPU: i7-10750H
 - RAM: 16g
 - MIDI application: Any
 - Version of the driver: 14.6.6

**Additional context**
None.

**Comment by FoxyBuddy** [comment]
After upgrading to 14.6.9, the error is still present. I can`t fix it!

**Comment by KaleidonKep99** [comment]
Can you please record a video of the issue? I have troubles reproducing it.

**Comment by FoxyBuddy** [comment]
Yes, I will upload a video as soon as I am idle. (The problem occurs randomly but is easier on large MIDIs.)
I tried to upload mdmp and debug text but they are too large to upload.

**Comment by FoxyBuddy** [comment]
Here is the video. I chose Satori Maiden 3rd eye 123 million to make the problem appears easier. The problem didn`t present a few updates ago.
https://user-images.githubusercontent.com/20873762/130004060-6db77fd1-21e9-49b9-aa8f-ccda5a035b7f.mp4

**Comment by KaleidonKep99** [comment]
Should work now, it's been almost 2 years oops.
