### ISSUE TITLE
Some UI components looks ugly because of the fonts

### ISSUE THREAD

**Issue by froggie3** [KaleidonKep99/OmniMIDI#204]
## Problem

Some UI components in OmniMIDI are displayed with MS Gothic UI, when I set the language setting of operating system to Japanese. This fonts breaks the UI components in the driver, and it won't happen in other European language settings.

Additionally, some windows can't be closed because of the problem.

## Expected behavior

All the user interface of the application should be displayed properly with beautiful anti-aliased fonts, but not as beautiful as it is.

## Screenshots

Just looks like this:

![20210822113136](https://user-images.githubusercontent.com/76399182/130340992-81b61bb9-746c-414b-8ccf-dd6d8be42a83.png)
![20210822113449](https://user-images.githubusercontent.com/76399182/130340994-59d2c0e9-824c-4210-ad31-c732bc59453e.png)
![20210822113239](https://user-images.githubusercontent.com/76399182/130340993-db6037fa-9d8b-43f4-bcd6-8d254ce94535.png)

## Environment
- OS: Windows 10 Professional / version 10.0.19042.1165
- Language: Japanese
- CPU: Ryzen 7 3700X
- RAM: 16GB
- Version of the driver: 14.6.9

**Comment by KaleidonKep99** [comment]
Yeah I don't know why this happens...
On Japanese versions of Windows, the Microsoft Sans Serif font gets replaced by... that?
I'll see what I can do about it.

**Comment by KaleidonKep99** [comment]
It should be fixed in 14.6.10.
