### ISSUE TITLE
OmniMIDI thinks MSYS2's setup wizard is a MIDI player

### ISSUE THREAD

**Issue by nerdgh0st** [KaleidonKep99/OmniMIDI#206]
**Problem**
OmniMIDI pulls up a KDMAPI initialization error when launching the MSYS2 setup wizard.

**Steps to reproduce**
1. Open MSYS2's setup wizard
2. See error

**Expected behavior**
No KDMAPI Error

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/68407522/130378808-033a62c3-b096-4195-88fe-373eea7166e5.png)

**Environment**
 - Operating system: Windows 10 Home 64-bit (10.0, Build 19043)
 - CPU: Intel Core i5 @ 3.10 GHz
 - RAM: 8GB
 - MIDI application: N/A
 - Version of the driver: 1.4.6.6

**Comment by KaleidonKep99** [comment]
You have an old WinMMWRP patch in the Downloads folder, and the setup is probably trying to load it (For some reason, some apps load WinMM even though they don't do anything audio related).

Delete winmm.dll from the Downloads folder, and the error will go away.
