### ISSUE TITLE
How to change output midi?

### ISSUE THREAD

**Issue by GuckTubeYT** [KaleidonKep99/OmniMIDI#207]
How to change output midi? is omnimidi have option change output midi?

**Comment by KaleidonKep99** [comment]
What do you mean? OmniMIDI *is* a MIDI output.

**Comment by GuckTubeYT** [comment]
> 
> 
> What do you mean? OmniMIDI _is_ a MIDI output.

no, i mean change the default midi output to omnimidi output

**Comment by KaleidonKep99** [comment]
Oh, like in the MIDI mapper?
You can install the OmniMapper tool by going to **"Extensions > OmniMapper"**, then you'll be able to access its configurator by going to **"Extensions > OmniMapper control panel"**.

**Comment by GuckTubeYT** [comment]
oh thanks
