### ISSUE TITLE
Problem with Piano From Above and OmniMIDI

### ISSUE THREAD

**Issue by Creatinator512** [KaleidonKep99/OmniMIDI#208]
**Problem**
Summary: PFA freezes occasionally and will remain even after closing. This bug seems to have some correlation to OmniMIDI due to a BASS error.
Description: After starting PFA and loading a MIDI, I immediately got an error message about BASS being started already with no description. However, PFA and OmniMIDI played the MIDI fine after that error. I loaded a different MIDI and got a warning message about a "DLL hell" where conflicts between two different libraries could result in weird crashes. But the MIDI was played fine again. I believe these two errors could correlate to an issue I've been having for a while where PFA's MIDI visualization freezes after trying to load a MIDI. Even after closing out of it, it can still remain, as shown in the screenshot.

**Steps to reproduce**
1. Play any MIDI on PFA-1.1.0-x86_64.exe
2. Either the BASS error will be displayed or more likely the application's visualization will freeze.
3. Try to play another MIDI
4. Nothing will happen if "frozen" and it may start not responding. If the BASS error happened prior to the second load, the DLL warning shows.
5. Closing out of PFA will result in the application still running in task manager.

**Expected behavior**
PFA should run without any errors or without freezing and it should close with the task ended.

**Screenshots/Videos**
![pfaFrozen_notClosing](https://user-images.githubusercontent.com/78432612/131720417-528388b4-071a-44e2-bb28-724758580f27.png)

**Environment**
 - Operating system: Windows 10 Pro, Version 21H1
 - CPU: Intel(R) Pentium(R) CPU G850 @ 2.90GHz (2 CPUs), ~2.9GHz
 - RAM: 4 GB
 - MIDI application: Piano From Above (Version 1.1.0)
 - Version of the driver: 14.6.9

**Additional context**
These problems happen by chance for me, so this issue isn't easily reproduceable, but this can happen fairly often. The BASS error started upon starting up my computer, then loading PFA and a MIDI.

**Comment by KaleidonKep99** [comment]
Do you have any other MIDI driver installed by any chance?

**Comment by Creatinator512** [comment]
OmniMIDI is the only one showing up for MIDI output.

**Comment by KaleidonKep99** [comment]
If the DLL hell message appears, that means that there's another program or driver loading its own BASS libraries into the process.

Could you please send the debug log here?

**Comment by Creatinator512** [comment]
Found the DLL hell error I was talking about after enabling troubleshooting mode. Here's the debug log that was created during that process.
[PFA-1.1.0-x86_64.exe (Debug output).txt](https://github.com/KeppySoftware/OmniMIDI/files/7100571/PFA-1.1.0-x86_64.exe.Debug.output.txt)
![pfaFrozen_errorSequence](https://user-images.githubusercontent.com/78432612/131887178-2befec79-d695-4032-a308-810fe3a5b23b.png)

**Comment by KaleidonKep99** [comment]
Can you check which MIDI devices are installed through the OmniMapper control panel?
If GetModuleHandle returns an handle to an already existing BASS lib in memory, then there MUST be something loading the libraries before OM is able to do so.

**Comment by Creatinator512** [comment]
OmniMIDI and Microsoft GS Wavetable Synth are the only ones showing up in the OmniMapper control panel.

**Comment by Creatinator512** [comment]
I think I had a glitched version of OmniMapper, because when I uninstalled the MIDI Mapper to access the control panel, everything started working as expected, even when I reinstalled it. I believe going through a couple updates without uninstalling and reinstalling it resulted in some problems between the driver and the mapper.

**Comment by Creatinator512** [comment]
Just got this error now. This is the BASS error I mentioned.
![pfaFrozen_bassError](https://user-images.githubusercontent.com/78432612/132048630-ad8050ff-b1a4-4512-834c-b4f7e6541b85.png)
The same warning and error sequence happened as well when I switched MIDIs, but now the Guru Meditation errors are changing.
![pfaFrozen_newGuruMeditationError](https://user-images.githubusercontent.com/78432612/132052073-0ea0a760-8a3a-454b-96e4-6a4a4e35209c.png)
After that, PFA started behaving as it did before this issue and OmniMapper is now mixed up again in installing or uninstalling it. Reinstalling OmniMIDI has worked in getting rid of the issue temporarily.

**Comment by Creatinator512** [comment]
Is this folder called "opt" in the System32 and SysWOW64 OmniMIDI folders with duplicate bass and bassmidi DLL files intentional?
![pfaFrozen_suspiciousFolder](https://user-images.githubusercontent.com/78432612/132080165-a13ac5ac-7cfa-481b-8cfd-43eb1886e470.png)
Also, I have attempted uninstalling anything that I could determine could be a culprit, but that has not worked.

**Comment by Creatinator512** [comment]
Deleting that folder has mostly fixed it. I started getting that same issue today and got this error after clicking "No" on the multiple bass libraries loaded warning.
![pfaFrozen_bassHandleError](https://user-images.githubusercontent.com/78432612/132971686-ef6aee8e-511a-4bc9-9edb-cae2520b7848.png)

**Comment by KaleidonKep99** [comment]
It should be fixed in 14.6.10.

**Comment by Creatinator512** [comment]
It's been a good amount of days without any errors, so it must be fixed. Thank you for your help in handling this problem!
