### ISSUE TITLE
Can't install - Download failed: success

### ISSUE THREAD

**Issue by ohno-ourtable** [KaleidonKep99/OmniMIDI#209]
**Problem**
Message box appears saying the download failed, with an error code of success.

**Steps to reproduce**
1. Run the installer,  and get to the part where it actually begins installing

**Expected behavior**
The driver should have installed without errors

**Screenshots/Videos**
https://imgur.com/a/IwkzqM0

**Environment**
 - Operating system: Ubuntu 20.04 (running under wine)
 - CPU: Intel i5-6300U (4) @ 3.000GHz
 - RAM: 8 GB
 - MIDI application: None
 - Version of the driver: 14.6.9

**Comment by KaleidonKep99** [comment]
OmniMIDI only supports Windows, since Wine doesn't support user-mode MIDI drivers.
Using the Windows Multimedia Wrapper will work, but to do that you need to fiddle around with the Wine configurator...

You can install .NET 4.8 yourself using winetricks.
