### ISSUE TITLE
Update check goes to unreleased version: 3.3.2.2

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#21]
The current latest version of Keppy's Driver is 3.3.2.1, but the updater says 3.3.2.2! Silly you! Seems like you forgot to release version 3.3.2.2 or use 3.3.2.1 as the latest version!

**Comment by KaleidonKep99** [comment]
I deleted version 3.3.2.2 because I'm pushing 3.4.0.0 soon.

**Comment by KaleidonKep99** [comment]
Like, I don't know, right now!
Here it is. [Version 3.4.0.0.](https://github.com/KaleidonKep99/Keppy-s-Driver/releases/tag/3.4.0.0)
