### ISSUE TITLE
Version 14.6.0's Legacy Panic (Shift + Insert) not resetting program changes/stopping all active voices

### ISSUE THREAD

**Issue by B00ie23** [KaleidonKep99/OmniMIDI#210]
**Problem**
Version 14.6 had it's panic feature reworked, and also kept the legacy panic function that not only stops all voices, but also resets all intruments. I noticed that the hotkey no longer resets intruments, but does stop all active voices (or does nothing at all depending on which shift key is used.)

**Steps to reproduce**
1. Play any MIDI with program changes (e.g Piano 1 to Elec. Guitar)
2. Use either L/R Shift + Insert combination
3. You'll either hear the panic stopping all voices, or you won't hear any changes at all

**Expected behavior**
Pressing Insert alone should stop all active notes, Shift + Insert should stop all voices and reset instruments, as listed in 14.6.0's changelog.

**Media resources**
https://user-images.githubusercontent.com/45867359/132978397-ad294c98-dca0-4724-8b15-465fca12b323.mp4
_(Note: I always have fast hotkeys enabled for panic to work)_
![OmniMIDIConfiguration](https://user-images.githubusercontent.com/45867359/132978509-86907628-c277-4592-a96a-5733019e9009.png)

**System environment**
 - Operating system: Windows 10 Home (21H1)
 - CPU: Ryzen 5 3600
 - RAM: 16 GB
 - MIDI application: Any (Domino was used to demonstrate)
 - Version of the driver: 14.6.9

**Additional context**
Although it isn't specified which shift key to use, I tried both and LShift + Insert does not do anything, RShift + Insert only stops all active voices. I even tried Control/Alt + previous combinations and that gave the same result.

**Comment by KaleidonKep99** [comment]
Will fix it shortly.

**Comment by KaleidonKep99** [comment]
Fixed in 14.6.10.
Sorry for the wait!
