### ISSUE TITLE
MIDI player error on 65K note sustain (sustain bomb v1.mid)

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#23]
MIDI player (e.g. MIDITrail) crashes when there are too many voices on sustain. [Example](http://youtu.be/6GQ6B2EUu5A)

**Comment by KaleidonKep99** [comment]
This is a problem in MIDITrail itself, not in my driver.

Closed.

**Comment by KaleidonKep99** [comment]
Also, that's BASSMIDI Driver. (Ethan reported me that Keppy's Driver didn't work on his PC)
