### ISSUE TITLE
Decoded data size stucks at 0

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#24]
![untitled](https://cloud.githubusercontent.com/assets/15729831/16736777/a7246c80-47b8-11e6-81c4-03df586c17cc.png)

**Comment by KaleidonKep99** [comment]
You have to restart the MIDI app when switching between XAudio and DirectSound.

**Comment by longnguyen2004** [comment]
Oh yeah. My bad :)
