### ISSUE TITLE
-advancedtab flag ("Change advanced settings)" goes to "List 1" tab instead of "Settings" tab

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#26]
When starting Keppy's Driver Configurator with the -advancedtab flag (e.g. "Change advanced settings" from start menu programs) will take you to the main list tab instead of the Settings tab. Thie flag used to work on older versions of Keppy's Driver, but in this version the flag has a glitch.

**Comment by KaleidonKep99** [comment]
I forgot to change the flag in the Inno Setup file from _-advancedtab_ to _/AT_*.

**Comment by KaleidonKep99** [comment]
Will be fixed on release 3.4.1.8.
