### ISSUE TITLE
Debug window freezes under high MIDI load (on low-end computer?)

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#27]
Every time I play RFTM-IS, when it reaches the heavy crash point, the debug window freezes. Just that.

**Comment by KaleidonKep99** [comment]
I guess it's your computer... 🚕

**Comment by longnguyen2004** [comment]
Probably (my W7 computer doesn't have this)

**Comment by KaleidonKep99** [comment]
The debug window started doing this since I "disconnected" it from the main configurator, I don't know why.

**Comment by KaleidonKep99** [comment]
The debug window from version 4.0.0.3 should work better.
[Try it and tell me.](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.0.0.3)

**Comment by longnguyen2004** [comment]
It seems to work better now.

**Comment by KaleidonKep99** [comment]
Ok, I guess I can close this then.
