### ISSUE TITLE
Driver rarely stopped working, needs to active Microsoft GS and reactive this driver again to work

### ISSUE THREAD

**Issue by Theblackmidi72** [KaleidonKep99/OmniMIDI#28]
I was enjoying MIDI with this driver, rarely happen:
Driver stopped working for randomly reason
It happen every program, not Piano from above, what cause this?

**Comment by KaleidonKep99** [comment]
Which version of the driver were you using?
Also, try increasing the buffer size to 20 or 25.

**Comment by longnguyen2004** [comment]
Try reinstalling the driver. If it still doesn't work, i'll look closer (mine worked perfectly)

**Comment by KaleidonKep99** [comment]
So...?

**Comment by Theblackmidi72** [comment]
It fixed
