### ISSUE TITLE
No longer default MIDI device

### ISSUE THREAD

**Issue by boink-182** [KaleidonKep99/OmniMIDI#29]
Issue experienced on Windows 10 64-bit (cannot speak to others): Since version 4.0.0.0, driver no longer installs as MIDI device #0. Prior to this the driver would always install as device #0 and programs that cannot explicitly select MIDI device would use it by default. Now there is no way to use the driver in such programs.

**Comment by KaleidonKep99** [comment]
You can fix the issue by setting the default MIDI device for Windows Media Player.
Tested it, and it works fine.

**Comment by KaleidonKep99** [comment]
Oh yea, forgot to say.
I actually did this on purpose.

I got a few complaints about Keppy's Driver/Synthesizer setting itself as default MIDI device, and not being able to change it back to something else.

**Comment by boink-182** [comment]
The registry key this changes only applies to Windows Media Player. Does not change default MIDI device for other programs. For instance, try with Media Player Classic Home Cinema. Could there be an option to install the driver as #0 in the future? I am stuck using 3.5.3.0 if I want to use the driver with certain programs, for instance eduke32, dxx-rebirth, etc.

**Comment by KaleidonKep99** [comment]
Great news! :)
![4.0.1.2 beta](https://i.imgur.com/z5HdPJI.png)

(This only shows up on Windows 8 and newer.)

**Comment by boink-182** [comment]
Awesome! Thank you so much :)

**Comment by KaleidonKep99** [comment]
Fixed. Here: https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.0.1.2
