### ISSUE TITLE
Reload soundfonts/lists text unchanged + Typo (old bug)

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#3]
![untitled](https://cloud.githubusercontent.com/assets/15729831/12694903/91d498e8-c76e-11e5-9624-83d81095e1fa.png)
![untitled2](https://cloud.githubusercontent.com/assets/15729831/12694904/91d5d8fc-c76e-11e5-9969-6034f3fba918.png)

**Comment by KaleidonKep99** [comment]
Fixed in the [3.0.0.2.](https://github.com/KaleidonKep99/Keppy-s-Driver/releases/tag/3.0.0.2)
