### ISSUE TITLE
When I try to open a MIDI Player with Keppy's Synthesizer 4.0.1.0 it can't open.

### ISSUE THREAD

**Issue by ghost** [KaleidonKep99/OmniMIDI#30]
When I try to open a MIDI Player with Keppy's Synthesizer 4.0.1.0 it can't open. I have 5 GBs of free memory and it still can't open any MIDI Player. Is there a way to fix this? (I also uninstalled and re-installed it and nothing changed).

**Comment by KaleidonKep99** [comment]
Does it happen with 4.0.1.3 too?
Make a video about the issue and post the link here.

**Comment by ghost** [comment]
OK, I updated the driver and now it works fine. Thank you.
