### ISSUE TITLE
GUI cannot Enable/Disable Watchdog.

### ISSUE THREAD

**Issue by boink-182** [KaleidonKep99/OmniMIDI#32]
Last 2 versions starting with 4.0.1.3 cannot Enable/Disable Watchdog via GUI. Must manually edit registry. GUI will show current state as found in registry, but cannot change from one to the other.

**Comment by KaleidonKep99** [comment]
Fixed. https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.0.1.5
