### ISSUE TITLE
Two MIDI Out devices?

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#33]
![screenshot_2](https://cloud.githubusercontent.com/assets/15729831/17937931/0ceb5238-6a4e-11e6-920e-4ae33b87e234.png)
I tried uninstalling any other synths that I have but it doesn't fix the problem.
Is that an intended feature or a bug?

**Comment by KaleidonKep99** [comment]
It's a bug in the MIDI Mapper patch.

**Comment by longnguyen2004** [comment]
I'll try removing the patch to see if anything change.

**Comment by longnguyen2004** [comment]
Yep, it's a bug in the patch, so I guess I can't do much about it.
