### ISSUE TITLE
"Reduce CPU overhead" causes audio issue even on W7

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#35]
It's probably not the ReactOS WMAPI that causes this. I tried this on my dad's W7 laptop and still has this issue (although Bandicam makes the audio a bit terrible since my CPU doesn't have hardware encoding but it still sounds way better when Reduce CPU overhead is disabled)
https://drive.google.com/open?id=0B-k9O996VHoLQlhHN29ydnFOQzA

**Comment by KaleidonKep99** [comment]
Your rendering time goes over 100%, and the driver resets itself.
Record a video with the debug window too, since this one isn't helpful at all.

**Comment by KaleidonKep99** [comment]
Here's what happens when using the ReactOS patch, and your audio seems fine, compared to this: https://drive.google.com/file/d/0B-jbdgbiY_-YcWhMM3dXTmEzQkU/view

**Comment by longnguyen2004** [comment]
You was right. My rendering time rises to near 100%.
