### ISSUE TITLE
miscellaneous error

### ISSUE THREAD

**Issue by sapphonie** [KaleidonKep99/OmniMIDI#36]
![image](https://cloud.githubusercontent.com/assets/15315481/19282748/924bf4ca-8fbd-11e6-87ee-93a32dedbaa2.png)

Occurs while trying to save soundfont settings.

**Comment by sapphonie** [comment]
I also get this error on starting the configurator:
![image](https://cloud.githubusercontent.com/assets/15315481/19282799/b1f8ecd8-8fbd-11e6-8b81-2c7e890ae351.png)

**Comment by KaleidonKep99** [comment]
Uninstall then reinstall the driver.

**Comment by sapphonie** [comment]
alright I'll try this

**Comment by sapphonie** [comment]
This worked. Closing.
