### ISSUE TITLE
PFA Freezes & Crashes

### ISSUE THREAD

**Issue by knock2one** [KaleidonKep99/OmniMIDI#37]
When I Open PFA With The XAudio Engine Enabled
![image](https://cloud.githubusercontent.com/assets/22779352/19288665/1db4b24c-8fd5-11e6-8c95-0a4be2e0f368.png)
PFA Crashes
![image](https://cloud.githubusercontent.com/assets/22779352/19288717/5bff01c4-8fd5-11e6-8698-6f154fc4c403.png)
 But When I Have The XAudio Engine Diabled 
![image](https://cloud.githubusercontent.com/assets/22779352/19288742/76c1c14a-8fd5-11e6-8fe6-97c7d6ba4cd2.png)
![image](https://cloud.githubusercontent.com/assets/22779352/19288777/a5524bf6-8fd5-11e6-898c-0bf472ab22be.png)
It Just Freezes

**Comment by KaleidonKep99** [comment]
Can you make a video of the issue, please?

**Comment by KaleidonKep99** [comment]
Could you also please share the details, since the "PFA has stopped working" window alone doesn't tell me a lot about the issue? lol

http://image.prntscr.com/image/678d419cec9540d789f89995acf492bb.jpeg

**Comment by KaleidonKep99** [comment]
Closed for: Missing information.
