### ISSUE TITLE
Keppy's Synthesizer does not work in some of MIDI Player Beyond 4.0.3.9 in Windows 7

### ISSUE THREAD

**Issue by Theblackmidi72** [KaleidonKep99/OmniMIDI#39]
![wha](https://cloud.githubusercontent.com/assets/21037985/19828656/5e8d92f0-9df6-11e6-9287-ceb5500e8e4b.PNG)

**Comment by KaleidonKep99** [comment]
![image](https://cloud.githubusercontent.com/assets/11065274/19828764/62ada0f4-9dcf-11e6-8055-eee348567fdb.png)

**Comment by Theblackmidi72** [comment]
4.0.4.0 still doesn't work
Also it doesn't work in miditrail too

**Comment by KaleidonKep99** [comment]
I guess your PC has some issues.
Have you tried unregistering and registering the driver back?
![image](https://cloud.githubusercontent.com/assets/11065274/19829202/f8e088e2-9dda-11e6-98a4-9517cc344a4f.png)

**Comment by KaleidonKep99** [comment]
So...?

**Comment by Theblackmidi72** [comment]
I try that and still doesn't work

**Comment by Theblackmidi72** [comment]
I am pretty sure I'm using windows 7 won't support, I try 4.0.3.8 and work
Beyond 4.0.3.9 not working anymore

**Comment by Cismontjoy** [comment]
![image](https://cloud.githubusercontent.com/assets/23145373/19834100/99d3244e-9e49-11e6-95ad-70add41ed3e0.png)
it seems to work fine on my system, idk what is going on yours

**Comment by Theblackmidi72** [comment]
I try again in win 7 aero still does not work

**Comment by Theblackmidi72** [comment]
It works on PFA and TMIDI ...
But some of them do not work like synthesia

**Comment by KaleidonKep99** [comment]
Are you using Windows 7 32-bit or 64-bit? Also, is the Service Pack 1 installed?

Try installing .NET Framework 4.0 from [there](https://www.microsoft.com/en-us/download/details.aspx?id=17851), then re-register the driver.

**Comment by Theblackmidi72** [comment]
Seems like it was bad problem,
I'm using VMS 2 now
Closing, Bye Keppy's Synthesizer!

**Comment by KaleidonKep99** [comment]
You didn't even bother fixing it or giving me info...
Oh well, that really helps me on resolving the issue.

Sigh...
