### ISSUE TITLE
Can't choose default synthesizer (already reported but unfixed)

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#4]
I remember that this has been reported before but it seems like you can't do it, so I report it again but also include a link to help you along the way:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/5b22e94c-37a9-4be5-ad55-3d9229220194/how-to-use-add-read-change-delete-registry-keys-with-vbnet?forum=vbgeneral

**Comment by KaleidonKep99** [comment]
I already know how to read and write on the registry, but I can't seem to find a way to make a synthesizer chooser.

**Comment by longnguyen2004** [comment]
I used Process Monitor to capture the registry keys that VMS changes when I choose another synthesizer. Here are the keys:
MIDI Mapper key:
HKCU\Software\Microsoft\Windows\CurrentVersion\Multimedia\MidiMap\szPname (default synth name)

Default MidiOut Device (the one VMS called WMP default synth) HKCU\Software\Microsoft\ActiveMovie\devenum{4EFE2452-168A-11D1-BC76-00C04FB9453B}\Default MidiOut Device
HKCU\Software\Microsoft\ActiveMovie\devenum 64 bit{4EFE2452-168A-11D1-BC76-00C04FB9453B}\Default MidiOut Device

For the default midiout device stuff to works, you need to read the Keppy's Driver midiout id (also in the 4EFE stuff) and replace the default midiout device's id with the driver's id.

**Comment by longnguyen2004** [comment]
Are you trying to fix this? Or you're still busy with the KMC?
PS: The BASSMIDI library is old, update it too.

**Comment by KaleidonKep99** [comment]
Still busy with Keppy's MIDI Converter.

**Comment by KaleidonKep99** [comment]
Fixed in version 3.1.0.1.
