### ISSUE TITLE
Best way to achieve low latency?

### ISSUE THREAD

**Issue by ghost** [KaleidonKep99/OmniMIDI#41]
I tried applying the "Low Latency" preset but there is still noticeable latency, unlike the 1ms claim on the readme
![image](https://cloud.githubusercontent.com/assets/22306952/20043278/59c4201e-a458-11e6-98e7-f321f74e26d5.png)

**Comment by KaleidonKep99** [comment]
You have to play with the settings by yourself, since the "Low latency" preset that ships with Keppy's Synthesizer has been tweaked to work with ALL the computers.

Some PCs might work with really small buffer settings, while others might not.

**Comment by KaleidonKep99** [comment]
Little update.

Keppy's Synthesizer got support for both ASIO and WASAPI, take a look at them when you can.
