### ISSUE TITLE
Sysex messages are always ignored when "Ignore Sysex messages" are enabled

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#43]
There is a bug with the new feature in Keppy's Synthesizer where Sysex messages are always ignored no matter when Ignore Sysex messages are enabled and disabled.

**Comment by KaleidonKep99** [comment]
They work just fine for me.
Remember that SysEx messages can ALSO be ignored by the application itself. (PFA doesn't recognize them, and VanBasco allow users to ignore them)

**Comment by KaleidonKep99** [comment]
I accidentally closed it oops.

**Comment by KaleidonKep99** [comment]
Also, let me know if the issue is still present in [version 4.0.5.1](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.0.5.1).

**Comment by KaleidonKep99** [comment]
It seems to work. Closed.
