### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#44]
The blacklist stopped working in later versions of the driver! When launching a MIDI program that is in the blacklist, the driver does not hide anymore and still visible.
![Blacklist bug, notice the selection is still there](https://cloud.githubusercontent.com/assets/8494722/21120875/1f621356-c08f-11e6-87a3-ff57df83dd16.png)

**Comment by KaleidonKep99** [comment]
I'll fix it now.

**Comment by KaleidonKep99** [comment]
Fixed as of version 4.0.5.2.
