### ISSUE TITLE
Suggestion: Ignore velocity 0/silent notes before sending to BASSMIDI

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#45]
Is it possible to ignore all silent notes before sending to BASSMIDI for synthesizing? Because black MIDIs often have ton of silent notes, doing this would prevent CPU time being wasted for synthesizing those notes (am I right?).

**Comment by KaleidonKep99** [comment]
BASSMIDI already ignores those notes, if I recall right.

**Comment by longnguyen2004** [comment]
I'm following up this topic on the un4seen forum. If you want to follow that, here's the link: http://www.un4seen.com/forum/?topic=17446.0

**Comment by longnguyen2004** [comment]
Have you checked the un4seen topic yet? Somebody pointed out how to get the velocity data from the DWORD you get from WinMM

**Comment by KaleidonKep99** [comment]
Added to Keppy's Synthesizer 4.0.5.3.
