### ISSUE TITLE
Blacklist system is broken

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#46]
Now every MIDI applications I use are blacklisted by KS (even though I haven't blacklisted anything).

**Comment by KaleidonKep99** [comment]
Clean the user blacklist.

**Comment by longnguyen2004** [comment]
I already tried cleaning it, doesn't work.

**Comment by KaleidonKep99** [comment]
It's weird, because I can use it just fine...

**Comment by longnguyen2004** [comment]
I'll try it on my other computer.

**Comment by longnguyen2004** [comment]
So the bug is only there if I blacklisted something (in my case, a VoIP program).

**Comment by KaleidonKep99** [comment]
Oh yea, now I see what the issue is.
It'll get fixed on version 4.0.5.6.

**Comment by KaleidonKep99** [comment]
Here: https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.0.5.6
