### ISSUE TITLE
VST Wrapper/Audio Out

### ISSUE THREAD

**Issue by kythre** [KaleidonKep99/OmniMIDI#48]
Could we get a VST wrapper and/or a way to chose where the audio is outputted?

**Comment by KaleidonKep99** [comment]
![image](https://cloud.githubusercontent.com/assets/11065274/21965922/9934e13c-db69-11e6-8d28-8ebda7c28d65.png)
![image](https://cloud.githubusercontent.com/assets/11065274/21965924/9f06470e-db69-11e6-8119-4c23fd4284c4.png)

**Comment by kythre** [comment]
Hey that's neat. Thanks.

**Comment by kythre** [comment]
I looked in there but didnt see it
I'm blind btw

**Comment by KaleidonKep99** [comment]
Closed.
