### ISSUE TITLE
"Enable sinc interpolation" should be grayed out when using XAudio

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#49]
![untitled](https://cloud.githubusercontent.com/assets/15729831/22548988/b64df02c-e97b-11e6-9160-578f3ab7b4bf.png)

**Comment by KaleidonKep99** [comment]
I restored the checkbox to work with both engines with update 4.0.5.9, since XAudio doesn't seem to apply sinc interpolation on all OSes.

Not a bug, but thanks anyway! :P
