### ISSUE TITLE
Default synthesizer settings doesn't work properly

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#5]
The default synthesizer settings is broken. First, it doesn't change the MIDI Mapper setting at HKCU\Software\Microsoft\Windows\CurrentVersion\Multimedia\MIDIMap.

Second, it doesn't work with 64bit programs because it only changes the devenum key, not them devenum 64bit one

Third, the ID are completely wrong. The settings says that the Keppy's Driver ID is 0 but the actual ID is 4 for 32bit and 2 for 64bit (sometime the ID can be different depends on the system, the number of synth installed, etc...).

This ID hell (It's my own name) can be fixed by read the individual ID for the 32 bit and 64 bit then change the default one accordingly.

**Comment by KaleidonKep99** [comment]
I'll look further into this.

**Comment by KaleidonKep99** [comment]
Fixed as of version 3.1.3.1.
