### ISSUE TITLE
Can't uninstall (

### ISSUE THREAD

**Issue by geekycow** [KaleidonKep99/OmniMIDI#51]
I can't uninstall version 4.0.6.15 from a fairly basic/minimalistic Windows 10 installation.  :(

If I select "Change or remove program-> Keppy's Synthesizer 4.0.6.15 (Uninstall only)-> Uninstall" then I get a dialog box saying "Runtime Error (at 097:93): Internal error: Cannot call "EXTRACTTEMPORARYFILE" function during Uninstall."

**Comment by KaleidonKep99** [comment]
I will fix it asap, thanks for reporting.

**Comment by KaleidonKep99** [comment]
Fixed as of [version 4.0.6.16.](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.0.6.16)
