### ISSUE TITLE
Complains about missing LoudMax.dll if "Create Desktop Icon" is unchecked during install.

### ISSUE THREAD

**Issue by khang06** [KaleidonKep99/OmniMIDI#52]
There isn't much else to say.

OS: Windows 10

**Comment by KaleidonKep99** [comment]
I don't have such issue, I tried re-creating it on clean Virtual Machines and on my physical machine.

**Comment by khang06** [comment]
Strange, it seems to happen on both of my machines.

**Comment by KaleidonKep99** [comment]
Maybe making a video about the issue could help me a bit more.

**Comment by KaleidonKep99** [comment]
https://www.youtube.com/watch?v=wEDpo1M7j28

**Comment by KaleidonKep99** [comment]
24 hours before I close the issue for *missing information*.

**Comment by khang06** [comment]
Damn, I can't seem to reproduce it either. Oh well.
