### ISSUE TITLE
Driver not working with audio frequency of 96,000Hz

### ISSUE THREAD

**Issue by ettolrach** [KaleidonKep99/OmniMIDI#53]
When I set the driver to use a frequency of 96kHz, the audio either doesn't work at all, or with crackles (see the video). Steps to re-produce:

(0. Reset to default)
1. Set your audio driver to work at 96kHz (or set it in Windows)
2. Set the preset to high fidelity audio
3. Set the frequency to 96000
4. Test the audio (I used Piano From Above)

The problem persists if you keep the application open, and set it to the high fidelity preset, however when you restart the application, it works fine.

Video of the problem: https://youtu.be/W_Dc_DuOmn8

**Comment by KaleidonKep99** [comment]
Using 96kHz with a buffer size of 20 is a suicide.
Increase the buffer size to at least 30, and if it doesn't work, increase by steps of 1 until it starts outputting audio.

**Comment by ettolrach** [comment]
Thanks, that worked
