### ISSUE TITLE
Triggers Easy Anti Cheat and Valve Anti Cheat

### ISSUE THREAD

**Issue by Kaydax** [KaleidonKep99/OmniMIDI#54]
Yah the title explains it. It got me almost ban from 2 games now

**Comment by KaleidonKep99** [comment]
I already talked with the Easy Anti Cheat team, and I have no issues with Valve Anti Cheat, I play Source games and others just fine.

Plus, they can't ban you for using Keppy's Synthesizer, it is NOT a cheat and it does NOT modify memory addresses on games.

**Comment by KaleidonKep99** [comment]
Easy Anti Cheat added the driver to their whitelist, while I did talk with the Steam Support, and they haven't found any issues with Keppy's Synthesizer and the Valve Anti Cheat.

Invalid, closed.

**Comment by Hri7566** [comment]
please look into this, i can't play halo or star wars

**Comment by Kaydax** [comment]
> please look into this, i can't play halo or star wars

The latest version of Omnimidi has 0 issues with any anti cheat. If you are still having issues then you should use the built in feature to block apps that omnimidi can hook into
