### ISSUE TITLE
Mask Roland MT-32

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#55]
I don't know if old DOS games rely on device name to identify MIDI devices or not, but please add the Roland MT-32 to the mask list. It would be nice to hear how old DOS games sound like with modern synth/soundfonts

**Comment by KaleidonKep99** [comment]
You can't mask an external MIDI synthesizer which relies on MIDI cables.
Windows will always detect such devices as "External synthesizer". (Or USB-MIDI Driver, if you use a USB to MIDI cable.)

**Comment by longnguyen2004** [comment]
I've just found out that DOSBox allows to choose MIDI devices to use, so problem solved?
