### ISSUE TITLE
Remove "Change the maximum samples per frame" and move "Ignore notes in between two velocity values"

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#56]
Since the option for changing the maximum samples per frame has been moved to the settings tab, why is it still in the "Additional settings" menu?
Also, I think that the "Ignore notes in between two velocity values" setting should be moved to the "MIDI events parser settings" submenu.

**Comment by KaleidonKep99** [comment]
Done with update 4.1.1.2.
