### ISSUE TITLE
Keeps complaining about BassMIDI driver being installed, I uninstalled it like 3 restarts ago...

### ISSUE THREAD

**Issue by fixylol** [KaleidonKep99/OmniMIDI#57]
My OS is Windows 10 64-bit (in case you need to know). I uninstalled BassMIDI and installed this, yet when I try to change the default MIDI driver or do anything related to MIDI files, it says it cannot run with BassMIDI installed.

**Comment by KaleidonKep99** [comment]
Check if the **"bassmididrv"** folder is still present in _"C:\Windows\System32\"_ and _"C:\Windows\SysWOW64\"_.
If it is, then delete it.

The BASSMIDI Driver's uninstaller is bugged, and doesn't uninstall the driver properly.

**Comment by KaleidonKep99** [comment]
24 hours remaining before I close this topic.

**Comment by KaleidonKep99** [comment]
I gave you extra 48 hours, and nothing... :/
Closed.
