### ISSUE TITLE
driver is not showing up in alt tab when window inside configurator is active

### ISSUE THREAD

**Issue by UnPrioritized** [KaleidonKep99/OmniMIDI#58]
title describes it all
stuff i found that is not working :
- Change default audio output
- Change pitch shifting
- Mask synthesizer as another
- Set reverb and chorus

**Comment by KaleidonKep99** [comment]
It shows up just fine (With the pitch shifting window, also idk why ShareX put a rectangle in my chats too rip): 
![image](https://cloud.githubusercontent.com/assets/11065274/25568060/32cfa294-2dfb-11e7-8236-1800d8fcb765.png)

And the mask works too: 
![image](https://cloud.githubusercontent.com/assets/11065274/25568070/663ae45e-2dfb-11e7-8837-982bdbaa03ef.png)

You can only change the default audio output when using DirectSound, and also the reverb and chorus are working too, you just need to enable the sound effects in the Settings tab.

**Comment by UnPrioritized** [comment]
ah it doesn't showing up on my side for some reason, i guess is my problem thanks for the help!

**Comment by KaleidonKep99** [comment]
Issue closed.
