### ISSUE TITLE
WASAPI engine does weird pitch shifting

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#59]
When I try to use WASAPI engine, it does some very weird pitch shifting
I know that I can use the built-in "Change pitch shifting" option, but with -1, the sound is still too high, while -2 makes it too low, it's just...annoying.

**Comment by KaleidonKep99** [comment]
Try [4.1.4.16](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.1.4.16).

Also, remember that both ASIO and WASAPI are meant for ultra-low latency environments, and they will not work properly with old/weak computers.

**Comment by longnguyen2004** [comment]
I'm currently having some problems with my computer, so I'll test it later

**Comment by KaleidonKep99** [comment]
Um...
Your PC is probably having problems that are affecting KS too. o:

**Comment by KaleidonKep99** [comment]
Also, remember to record a video of the issue, because telling me "WASAPI engine does weird pitch shifting" doesn't really help me on solving the issue... 😃

**Comment by longnguyen2004** [comment]
It's about custom themes (Windows 10 theme system is messy :D )
Anyway, the problem seems to be fixed.
