### ISSUE TITLE
Refuses to load even if no other synth is installed?

### ISSUE THREAD

**Issue by minelolpride** [KaleidonKep99/OmniMIDI#6]
I have had both Coolsoft VMS versions (1.x, 2.x) uninstalled for quite some time since I started using this driver. The function of refusing to load alongside VMS 1 is pretty good, but for me, it seems to still find it installed even though there isnt a trace leftover.

![1](https://cloud.githubusercontent.com/assets/16008698/13573766/6fab3e2e-e43e-11e5-997a-03ad650525e6.JPG)
![2](https://cloud.githubusercontent.com/assets/16008698/13573768/6fb33a70-e43e-11e5-8fee-f676fd2b2144.JPG)
![3](https://cloud.githubusercontent.com/assets/16008698/13573767/6fb2de0e-e43e-11e5-91d1-9f4f862ad054.JPG)

This issue began happening immediately after install of 3.0.1.6.

**Comment by minelolpride** [comment]
This problem seems to have fixed itself after restarting my laptop... It is weird though how it thought VMS 1 was installed in the first place...

**Comment by KaleidonKep99** [comment]
If VMS asks you to restart the PC after you uninstalled it, please do.
My driver checks if VirtualMIDISynth.dll is inside System32.
