### ISSUE TITLE
Suggestion: Add an OSD

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#60]
It would be nice to have an OSD that display the active voices, rendering time etc. so I don't need to have the debug window taking up space.

**Comment by KaleidonKep99** [comment]
OSD? You mean a screen overlay or something like that?
I could do that, but it would require a lot of CPU power, since it's all software accelerated.

**Comment by longnguyen2004** [comment]
You can try to build your OSD with RivaTuner Statistics Server (is that even hardware-accelerated?) because I've seen programs using that for OSD. Of course, it only works for programs that use DirectX or OpenGL (like PFA, Synthesia etc.), but it's kinda pointless for normal MIDI programs anyway.

**Comment by KaleidonKep99** [comment]
That would just make me waste time... Why would I need to spend time to create an add-on for RTSS, just for this?

**Comment by longnguyen2004** [comment]
ehh ok, I guess you can close it now :)
P.S: Since I'm currently on the Canary branch, can you change my role on the update server?

**Comment by KaleidonKep99** [comment]
Done.
Closed.
