### ISSUE TITLE
Percentage sign doesn't move when resizing window

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#61]
![untitled](https://cloud.githubusercontent.com/assets/15729831/25937640/ad532938-3656-11e7-8d25-b9a5eabc5f92.png)
![untitled](https://cloud.githubusercontent.com/assets/15729831/25937663/bd55e686-3656-11e7-8e32-d43dbf029a42.png)

**Comment by KaleidonKep99** [comment]
Fixed as of version [4.1.5.2](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.1.5.2).
