### ISSUE TITLE
switch list hotkeys sometimes dont function

### ISSUE THREAD

**Issue by minelolpride** [KaleidonKep99/OmniMIDI#62]
when playing a MIDI and attempting to swap soundfont lists, sometimes it doesn't actually switch lists at all, leaving me to mash ALT+# to change sf lists every now and then.
i have basically ruled out everything i could to make sure that it wasn't something to do with my inputs being picked up incorrectly somewhere, and it has occurred on multiple systems in my possession as well

**Comment by KaleidonKep99** [comment]
Because it checks if you pressed the hotkey every 100ms.
