### ISSUE TITLE
output to WAV not outputting file

### ISSUE THREAD

**Issue by minelolpride** [KaleidonKep99/OmniMIDI#64]
when attempting to use the 'Output to WAV' mode inside of the synth, it seems as it if wont actually output any file whatsoever (it also doesnt stop sound output to the speakers too, which shows that it doesnt seem to try?)

video of the problem: https://youtu.be/LXN7pah5Od4
(you can use the video as a visual '_how to recreate the issue_' guide from me)

note: i was trying to see if i could create a debug log for you to look at, but it doesnt want to output one either?
note 2: not sure if intentional or not; switching from .WAV mode doesnt retain some previous settings from before switching it on.

**Comment by KaleidonKep99** [comment]
*Response to note 2*: Yes, it is completely intentional.

It'll be fixed on version 4.2.1.1.

**Comment by KaleidonKep99** [comment]
Fixed as of version [4.2.1.1](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.2.1.1).
