### ISSUE TITLE
Soundfont lists changing doesn't work

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#66]
I tried changing from list 2 (Flashback D-274) to list 3 (Steinway B-211) but it wouldn't change to list 3, even after many times hitting alt-3. Even trying to assign list 3 to Synthesia, it's still at list 2

**Comment by KaleidonKep99** [comment]
Can not reproduce issue.
Your antivirus is probably messing up with Keppy's Synthesizer's registry keys.

Closed.
