### ISSUE TITLE
Applying WinMM patch to program breaks USB midi

### ISSUE THREAD

**Issue by daredevil28** [KaleidonKep99/OmniMIDI#67]
When you apply the patch to Synthesia or Piano from Above, it makes it so that it can't use any USB midi keyboards. 

Not tested with any other midi program.

Unpatching fixes the problem.

**Comment by KaleidonKep99** [comment]
ReactOS doesn't support MIDI inputs yet, that's why the patch doesn't support them too.
The patch is based on files from the ReactOS project.
