### ISSUE TITLE
Suggestion: Combining full installer and updater

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#68]
Since the updater file and full installer isn't that different in size, can you just combine the two to prevent confusion? You can make it does a check to see if the driver's already installed, then carry on with the updater.

**Comment by KaleidonKep99** [comment]
They're not the same.
One doesn't require administrator permissions, allowing non-admins to upgrade the driver without the need for an admin, while the other does, and also writes crucial registry keys for it.
