### ISSUE TITLE
Few lasts versions crashs 32 bit MIDI Players and Editors

### ISSUE THREAD

**Issue by DixelU** [KaleidonKep99/OmniMIDI#69]
Few days ago after another KS update i got Domino and Sekaiju dead. It wont start at all, crashes immediately after clicking. With using Visual Studio's debugger i found what it stops on intializing keppysynth.dll...
After rolling back to 4.3.1.1 everything again works fine.

**Comment by KaleidonKep99** [comment]
![image](https://user-images.githubusercontent.com/11065274/28069300-427ea74a-6649-11e7-86ce-6cf758f5fbd8.png)
Try disabling this function in KS 4.3.1.3.

**Comment by DixelU** [comment]
It was turned off all the time.

**Comment by KaleidonKep99** [comment]
Quite weird... I mean, there are no substantial differences between 4.3.1.1 and 4.3.1.2.

Try enabling the debug log.
When the app crashes, post the debug log here.

You can find the debug log at **"%userprofile%\Keppy's Synthesizer\debug"**.

**Comment by DixelU** [comment]
Also apps works fine when used DirectSound
here log what has been created after starting with XAudio
[Domino.exe - Debug Output.txt](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/files/1140835/omino.exe.-.Debug.Output.txt)

**Comment by KaleidonKep99** [comment]
Try this version of Keppy's Synthesizer: http://kaleidonkep99.altervista.org/dl/KeppysSynthSetup.exe

**Comment by DixelU** [comment]
Now works fine! Thanks

**Comment by KaleidonKep99** [comment]
Alright. I'll publish an official release now.
