### ISSUE TITLE
Certificate security concerns

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#70]
I noticed that you're using SHA-1 for your certificate. SHA-1 is basically broken by now (go to shattered.io for more info) so you should use something better.

**Comment by KaleidonKep99** [comment]
Yeah this was just a test, I was going to release a new SHA512 certificate this morning, but I forgot about it.

https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.3.3.3
