### ISSUE TITLE
Piano From Above sound stops after 1-2 minutes.

### ISSUE THREAD

**Issue by mbms0** [KaleidonKep99/OmniMIDI#72]
On the latest release (4.4.0.0) when I open PFA with Keppy's Synthesizer, the MIDI sound stops after a few moments and I have to close and reopen PFA. It actually happens only on PFA, because in FL Studio the sound is fine all the time.

**Comment by KaleidonKep99** [comment]
Could you give me more info?

What are your settings for the driver? Did you unlock the framerate on Piano From Above?

**Comment by mbms0** [comment]
Here is a video which contains all what you need to know (my settings, how the sound stops). Also if I unlock the framerate on PFA it will crash; I have tried that.

https://drive.google.com/open?id=0BzBbZ2xPcty6WjdLRkRXRHdhaWc

**Comment by KaleidonKep99** [comment]
Your PC is too weak. Increase the buffer size to 30, or switch to WASAPI.
You should've tried doing that yourself, instead of creating this topic though.

**Comment by mbms0** [comment]
Ok, now it worked but I don't know anything about these things so I couldn't have done this.

**Comment by KaleidonKep99** [comment]
Then don't use this driver. It's targeted to professionals, use VirtualMIDISynth instead.
