### ISSUE TITLE
MT-32 mode

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#73]
Can you add an MT-32 mode that rearrange the instruments according to the MT-32 layout? That way, I can play old DOS games that use the MT-32 with modern synth.

**Comment by KaleidonKep99** [comment]
I'll look into it.

**Comment by longnguyen2004** [comment]
Are you getting some trouble? I'm not pushing you or anything, I just want to help you.
If you need the instruments layout, here it is: http://www.voidaudio.net/mtinstrument.html

**Comment by KaleidonKep99** [comment]
The issue is that BASSMIDI does support MT-32 natively, but some games/applications in DOSBox don't send the required channel data to the driver.
All the channels get shifted by one, so Channel 1 is muted, and Channel 11 is the drum channel.

I'll talk with Ian about it.

**Comment by longnguyen2004** [comment]
Actually, the MT-32 only has 9 channels, in which the last one is drum. So it's assigned to MIDI channel 10. That resulted in the first channel being assigned to MIDI channel 2 (simply because the MT-32 doesn't have enough channels). And after all, games will output the MIDI data to the correct channels. It's only the instruments layout that need fixing.

**Comment by KaleidonKep99** [comment]
It's actually wrong.
Channel 1 will not work at all, while Channel 2 and onwards will.

I tested this with both a real MT-32 synth, and MUNT.

**Comment by longnguyen2004** [comment]
I know that the MT-32 ignores MIDI channel 1, but i still don't know if the drum channel is still linked to MIDI channel 10 or not (I have some MT-32 specific MIDIs and the drum are still where it used to be)

**Comment by KaleidonKep99** [comment]
Added as of version 4.4.1.5.
