### ISSUE TITLE
.sfz isn't associated + broken links

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#75]
I've noticed that .sf2 does get associated but not ,sfz. Is there any reason for this?
Also, the 2 links in the Settings tab, "Engines?" and "What's WAV mode?", is broken (they don't do anything)

**Comment by KaleidonKep99** [comment]
I'm aware of that! I'll fix them in the next release, I'm currently working on some stuff. 😋

**Comment by KaleidonKep99** [comment]
Fixed as of version 4.4.1.6.
