### ISSUE TITLE
Adjustable debug log

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#78]
Can you add an option to adjust the debug log? Since I don't want KS to dump absolutely everything into the log, I just want to dump errors and warnings.

**Comment by KaleidonKep99** [comment]
Will do.

**Comment by KaleidonKep99** [comment]
https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.5.0.2.
