### ISSUE TITLE
instruments keep changing to normal notes when playing

### ISSUE THREAD

**Issue by AG89** [KaleidonKep99/OmniMIDI#79]
Example: https://instaud.io/1o2Q

Idk if it's an driver problem that i only have but it doesn't seem to be going away. I'm thinking of just getting the older update of the driver because i didn't have the problem then.

**Comment by KaleidonKep99** [comment]
![image](https://user-images.githubusercontent.com/11065274/32138386-083a075c-bc32-11e7-9f5e-9a075173b612.png)

Disable this feature, in the mixer.

**Comment by AG89** [comment]
Yeah... I forgot to disable it the whole time.
