### ISSUE TITLE
Synthesia 10.4 broken

### ISSUE THREAD

**Issue by MaddieMewmews** [KaleidonKep99/OmniMIDI#80]
Keppy's Synthesizer does not work with Synthesia 10.4, After some [research](https://www.synthesiagame.com/forum/viewtopic.php?f=6&t=8797) I discovered that the problem was caused by *Windows 10's new MIDI infrastructure*. Thanks in advance.

**Comment by KaleidonKep99** [comment]
I'll add support for the WinRT MIDI API soon.

**Comment by KaleidonKep99** [comment]
Apparently, WinRTMIDI can only be used on kernel-mode drivers for now.
I'll wait for Microsoft to add support for user-mode drivers as well.
