### ISSUE TITLE
Possible Linux version of Keppy Synthesizer?

### ISSUE THREAD

**Issue by Warriors-Blade** [KaleidonKep99/OmniMIDI#81]
I was curious if this awesome program would ever have a Linux version as well.

So far I can not find any alternatives to Keppy on Linux.

**Comment by KaleidonKep99** [comment]
I'm currently not planning on porting Keppy's Synthesizer to Linux.
There's a valid alternative though, which is called QSynth. You should give it a try.

**Comment by FireController1847** [comment]
QSynth is really bad for black midi's tbh, haven't had a good experience with it at all.
