### ISSUE TITLE
Electron not detecting Keppy's Synth as a possible MIDI output?

### ISSUE THREAD

**Issue by FireController1847** [KaleidonKep99/OmniMIDI#82]
Now I don't know if this is an issue with Electron or Keppy's Synth, but I came here first (because loopMidi shows fine). When running the test code below:
```js
navigator.requestMIDIAccess().then(midi  => {
  for (const item of midi.outputs) {
    console.log(item[1]);
  }
}).catch(console.error);
```
If you run it in Google Chrome, you'll see that Keppy's Synth shows up as an option (so does loopMidi for me). But if you run it in an Electron app, say, Discord, by pressing CTRL+SHIFT+I and then pasting it into there, you'll see the only outputs available are loopMidi if you have it, but no Keppy's Synthesizer.

**Comment by KaleidonKep99** [comment]
It's up to the app developer to disable certain MIDI support functions in the Electron engine.

**Comment by FireController1847** [comment]
What? That's not the issue lol. First, I am the app developer, second, the issue is that it doesn't show up at all in Electron while it does in Google Chrome.

**Comment by KaleidonKep99** [comment]
Well, you didn't specify you were the developer. 🤔
Chromium had issues with MIDI devices, and they fixed them recently, after some Nightly builds.

Maybe Electron is using an oudated release of Chromium, I'm not sure.

**Comment by FireController1847** [comment]
Yea, sorry about that lul.

I'll bring up an issue in https://github.com/electron/electron/ referencing this one to see if it's an issue there.

**Comment by KaleidonKep99** [comment]
Also take a look at this, it might help the Electron team: https://bugs.chromium.org/p/chromium/issues/detail?id=672793

**Comment by KaleidonKep99** [comment]
Anything new about it?

**Comment by FireController1847** [comment]
No, this bug still seems to be there. No responses on the electron issue either.

**Comment by KaleidonKep99** [comment]
👀

**Comment by FireController1847** [comment]
It got tagged, hopefully will be fixed eventually.

**Comment by KaleidonKep99** [comment]
I'll close this, since it's not an issue with Keppy's Synthesizer itself.
Let's see if the Electron team updates their CEF build... 🤷‍♂️
