### ISSUE TITLE
Bass Execution Error

### ISSUE THREAD

**Issue by FireController1847** [KaleidonKep99/OmniMIDI#84]
Not sure how to describe it. Doing the instructions at the bottom. Caused by opening vanBasco's Kareoke Player and selecting Kepp's as the output. Didn't have this issue before, no other auto devices open.

![](https://imgur.com/jZDwQW5.png)

**Comment by KaleidonKep99** [comment]
As stated in the error dialog, another app might've took exclusive use over the selected audio output.
Try selecting a custom audio output through Keppy's Synthesizer itself.

![immagine](https://user-images.githubusercontent.com/11065274/36185556-07a8da86-113a-11e8-973b-9a8cbd18911e.png)
![immagine](https://user-images.githubusercontent.com/11065274/36185559-0cf76a70-113a-11e8-9cd6-8877f8a3a61f.png)
![immagine](https://user-images.githubusercontent.com/11065274/36185566-1984e6fa-113a-11e8-84f3-7f30d688c353.png)

**Comment by FireController1847** [comment]
Of course, I forgot that I used that earlier to switch from my speakers to my headphones. I can't believe I didn't think of that! xD Thanks! Also, thanks for this wonderful synthesizer!

**Comment by KaleidonKep99** [comment]
No problem!
