### ISSUE TITLE
Broken GUI scale for configurator on 1920x1080 screen makes saving settings impossible on 4.5 and above

### ISSUE THREAD

**Issue by stgiga** [KaleidonKep99/OmniMIDI#85]
Dear Keppy, great job with your program. You have truly made the best MIDI synth. I have a few issues to inform you about. Firstly, on any version beyond 4.2.2.5, the configurator window is too small to show the lower options, and too small to show the save settings button. I also found out live settings does not work either in these versions. This makes it impossible to use the newer versions. Secondly on the announcements discord, the link to your soundfont page is 404'd. Thirdly, DOSBOX-X is a VS2017 program that DOES run on 2000sp4/XP. I am not asking that you make it run on 2000/XP or Vista SP0, but that you tell would-be forkers that it is possible if the user is dedicated enough to rework it. Other than that, on my Realtek HW, DSound has no sound. I do have a PC that can run everything maxed out, so I do not have to worry.

**Comment by KaleidonKep99** [comment]
![immagine](https://user-images.githubusercontent.com/11065274/36396361-0d73c6aa-15be-11e8-99d5-92745011ae8c.png)
It seems to work fine on my end.
I'll try on a Windows 7 machine too.

About the live settings not working properly, try reinstalling the driver from scratch.

And about VS2017. I do know that it still supports XP.
But my driver uses a version of VS2017 which only supports Vista SP1 and newer, which includes new calls that aren't supported by XP. (vc141. VS2017 for XP is vc141_xp)

**Comment by stgiga** [comment]
I used a windows 10 version with the newest update. I have a maxed out nVidia GeForce GTX 950M AND Integrated Intel HD graphics. I do not have a touch screen. I have 1080p resolution.

**Comment by stgiga** [comment]
Turns out win10 had the dpi messed up... it is fixed. Also, does it work with reactos?

**Comment by KaleidonKep99** [comment]
The driver does NOT work with ReactOS **(for now)**, since it simulates a Windows Server 2003 environment.
Maybe it will, in the future, just like Wine.

Closed.
