### ISSUE TITLE
Trying to play Black MIDI on MIDITrail

### ISSUE THREAD

**Issue by KylesDigitalLab** [KaleidonKep99/OmniMIDI#86]
https://i.kyle2000.ml/4ci0r.png

**Comment by KaleidonKep99** [comment]
Patch the program with the ReactOS patch, and enable the slow playback mode in the advanced audio settings.
Slow playback doesn't affect the graphics in MIDITrail.

**Comment by KylesDigitalLab** [comment]
Isn't ReactOS a custom OS? I'm running Windows 10. Is it a patch for ReactOS that does stuff on Windows 10 also?

**Comment by KaleidonKep99** [comment]
It just pastes two files from ReactOS inside the MIDI app's directory, it does NOT modify your Windows installation.

The patch is removable, you just need to delete two files from the MIDI app's directory:
- wdmaud.drv
- winmm.dll

**Comment by KylesDigitalLab** [comment]
Okay/

**Comment by KylesDigitalLab** [comment]
Thank you, it looks like my MIDIs are better with no problems. You can close this issue.

**Comment by KaleidonKep99** [comment]
Closed.
