### ISSUE TITLE
Discord Rich Presence strange behavior

### ISSUE THREAD

**Issue by minelolpride** [KaleidonKep99/OmniMIDI#87]
I have noticed on the recent 5.0.2.4 update that the implementation of Discord's Rich Presence has been behaving oddly, and seems to be also quite slow (especially when closing the configurator)
When enabling the feature, the option will appear to disable itself when closing and re-opening the configurator, leaving me confused as to whether the option _actually_ disables itself when the configurator is closed or not (knowing that it takes multiple minutes for Discord to catch up to the window being closed).

Video of issue: https://youtu.be/MjC8QJaUJu0

After long enough, Discord will stop showing as 'Tampering with the settings', but will instead show no additional text instead: 
![capture](https://user-images.githubusercontent.com/16008698/36516191-18529c40-173a-11e8-8eab-1529768e57ef.PNG)
Eventually Discord will stop showing KS as the active program / game (it takes about a minute or so for it to catch up from that point.)

**Comment by KaleidonKep99** [comment]
It's Discord's fault if the Rich Presence updates so slowly. It takes a while for it to update, usually up to 5 seconds.
Disabling the Rich Presence only removes the current status, while still displaying it as a game.

I'll fix the issue with the setting now.
