### ISSUE TITLE
WinMM Patch Makes LoopMidi Disappear?

### ISSUE THREAD

**Issue by FireController1847** [KaleidonKep99/OmniMIDI#88]
I'm not sure how much this applies to KS itself, but when I applied the WinMM patch (which I'm quite uninformed about), loopMidi completely disappears as an option as well as Microsoft's synth (although idgaf about the Microsoft one). This happened to both PFA and Vanbasco's Kareoke Player.

**Comment by KaleidonKep99** [comment]
Microsoft GS Wavetable Synth is "hard-wired" into WinMM, so that's why it disappears when using the ReactOS Multimedia system.
And the patch doesn't support MIDI inputs, the ReactOS team hasn't implemented it yet.

**Comment by FireController1847** [comment]
Damn. Okay, thanks!

**Comment by KaleidonKep99** [comment]
I don't know if you tested the new Windows Multimedia Wrapper patch, but it allows users to bypass WinMM without losing MIDI input support.
