### ISSUE TITLE
Toggling sound effects forcefully switches to List 1 soundfonts

### ISSUE THREAD

**Issue by minelolpride** [KaleidonKep99/OmniMIDI#89]
Reproduce:
> 5.0.2.13
> Load soundfonts in lists outside of 1
> Start playing midi
> Toggle the sound effects on/off

Video:
https://youtu.be/p5uEvXqWvxo

Notes:
In the video I show the bug occuring with an SFZ format soundfont, as I had thought that had something to do with this, though I quickly realized that wasnt the case and it would reload list 1 no matter what.

edit: link fix

**Comment by KaleidonKep99** [comment]
Fixed as of version 5.0.3.0.
