### ISSUE TITLE
Lag with Bluetooth Speakers/Headphones

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#9]
When I try to listen to MIDI files using Piano From Above with my speaker connected to Bluetooth, the sound lags a lot. I tried changing the buffer to 1000 and it didn't work. I also tried changing the max voices or the max percentage, but same problem.

**Comment by KaleidonKep99** [comment]
What do you mean by LAG?
There's a big delay between the key-press and the actual audio of the piano?
Also, the bigger the buffer is, the bigger is the delay...

**Comment by KaleidonKep99** [comment]
Also, you set the buffer to 1000?????
It's limited between 1 and 100.

**Comment by DevanWolf** [comment]
I meant the sound keeps clicking and stuttering and it annoys me!

**Comment by KaleidonKep99** [comment]
Have you tried setting the buffer to 10?
Also, XAudio is really not meant for Bluetooth speakers, have you tried disabling it?

**Comment by DevanWolf** [comment]
Yes, I tried disabling XAudio and set the buffer to 10. But it still keeps lagging!
I had to restart the MIDI application to use the changed buffer of 100 (sort of)

**Comment by KaleidonKep99** [comment]
Does VirtualMIDISynth do the same?
Also, you obviously need to restart the MIDI application after changing the buffer...

**Comment by KaleidonKep99** [comment]
So... I guess... I can close this issue now.

And seems you're the only one with this problem, because I tried different Bluetooth speakers on different computers, and they all work just fine.

_Closed._
