### ISSUE TITLE
I have uninstalled every synth i have

### ISSUE THREAD

**Issue by GamingMidi** [KaleidonKep99/OmniMIDI#90]
it says Keppy's Synthesizer can NOT work while BASSMIDI Driver is installed.
The driver will not work until you uninstall BASSMIDI Driver.

Click OK to continue.
but i uninstalled everything about synthesizer's on my pc exept for Keppy's Synth
HELP

**Comment by KaleidonKep99** [comment]
You have to delete the folders manually, since the BASSMIDI Driver uninstaller doesn't work properly.

Boot into safe mode, and delete:
- C:\Windows\System32\bassmididrv
- C:\Windows\SysWOW64\bassmididrv *(If you have a 64-bit system)*
