### ISSUE TITLE
Node.js MIDI Package Not Detecting Keppy's Synthesizer

### ISSUE THREAD

**Issue by FireController1847** [KaleidonKep99/OmniMIDI#91]
Possibly related to #82, [this module](https://www.npmjs.com/package/midi) does not show Keppy's Synthesizer as a valid option, leading me to believe that maybe it's not an electron issue and it's a Keppy's Synthesizer. Could it be a driver or something you're using?

Example code:
```js
const midi = require('midi');
const output = new midi.output();

// List Ports
console.log('Listing MIDI Ports...');
for (let i = 0; i < output.getPortCount(); i++) {
  console.log(`Port ${i}: ${output.getPortName(i)}`);
}
```

Expected output:
```
Port 0: Microsoft GS Wavetable Synth 0
Port 1: Midi Loop 1
Port 2: Keppy's Synthesizer
```

Actual output:
```
Port 0: Microsoft GS Wavetable Synth 0
Port 1: Midi Loop 1
```

**Comment by KaleidonKep99** [comment]
Try messing around with the driver mask, in the configurator.

**Comment by FireController1847** [comment]
Alright, just tried all different types available as well as renaming the port to no avail.

**Comment by KaleidonKep99** [comment]
I tested version [5.0.3.21](https://github.com/KeppySoftware/Keppy-s-Synthesizer/releases/tag/5.0.3.21) with Node.js myself, it's detected now.
Have fun with it! 📦

**Comment by FireController1847** [comment]
May I ask, what's the blacklist file for?

**Comment by FireController1847** [comment]
May I ask what node version you used? It's still not showing up for me. Here's my output. (I also tried on the latest node 8 version)

On KS 5.0.3.21 (5.0.3 CR21)

```sh
E:\Development\Local\MPPMidi\src>node -v
v9.11.1

E:\Development\Local\MPPMidi\src>npm -v
5.6.0

E:\Development\Local\MPPMidi\src>node ports.js
Listing MIDI Ports...
Port 0: Microsoft GS Wavetable Synth 0
Port 1: loopMIDI Port 1
```

**Comment by KaleidonKep99** [comment]
I used Node.js 8.11.1 LTS.
Delete keppysynth.dbl from C:\Windows\SysWOW64\keppysynth, then update the driver. Let me know if that works.
Also register the driver again, just in case an audio driver update messed up the registry keys.

**Comment by FireController1847** [comment]
Ah, there it is. I had an issue in the installation process, works now. Thanks!
