### ISSUE TITLE
loading sflists with specified presets fails

### ISSUE THREAD

**Issue by Sub-Zero** [KaleidonKep99/OmniMIDI#92]
Running version 5.1.1.1
To replicate
1. check 'import specific bank'
2. select soundfont
3. pick a preset (I mapped preset 10 to preset 10, bank 0 for both)
4. export sflist
5. clear list
6. attempt to import list
it fails with
"System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at KeppySynthConfigurator.KeppySynthConfiguratorMain.IEL_Click(Object sender, EventArgs e)"

test.sflist:
C:\music\soundfonts\SGM-V2.01\SGM-V2.01.sf2
p0,10=0,10|C:\music\soundfonts\arachno-soundfont-10\Arachno SoundFont - Version 1.0.sf2

It works fine without import specific bank.  I also tried a path without spaces, and a filename without extra periods, as well as double \ in place of single in the path. No change.

**Comment by KaleidonKep99** [comment]
It'll be fixed on the next release.

**Comment by KaleidonKep99** [comment]
Fixed in [version 5.1.1.2](https://github.com/KeppySoftware/Keppy-s-Synthesizer/releases/tag/5.1.1.2).

**Comment by Sub-Zero** [comment]
Great, thanks.
