### ISSUE TITLE
Send midi input straight to Keppy's synth.

### ISSUE THREAD

**Issue by PatrickGuthridge** [KaleidonKep99/OmniMIDI#93]
Through the mixer or something, so that there is no need for an external program to here my piano through pc speakers.

**Comment by KaleidonKep99** [comment]
I'll add this feature to the configurator.

**Comment by KaleidonKep99** [comment]
Added in [version 5.1.1.2](https://github.com/KeppySoftware/Keppy-s-Synthesizer/releases/tag/5.1.1.2).

**Comment by PatrickGuthridge** [comment]
Works well. Thank you.
