### ISSUE TITLE
I can't Use The Synth

### ISSUE THREAD

**Issue by GamingMidi** [KaleidonKep99/OmniMIDI#98]
When ever i go to patch PFA i get an error
![csrss_2018-06-11_01-44-28](https://user-images.githubusercontent.com/38268687/41222462-c23ce904-6d1b-11e8-899f-317d64997aa7.png)
I can't select the synth eather 
![pfa-1 1 0-x86_64_2018-06-11_01-42-07](https://user-images.githubusercontent.com/38268687/41222482-d2671476-6d1b-11e8-931d-89a8a91f3be4.png)
Im not sure what the issue is... Help meh

**Comment by longnguyen2004** [comment]
Have you repatched PFA? You have to repatch because of the name change

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
